### PR TITLE
fix: Don't fail acceptTeamInvitation for duplicate suggested actions

### LINKED ISSUE #10085: Invite Links not working
We've had a handful of inquiries from users stating the invite links are not working. User trying to accept invites are stating they are receiving a server error message or nothing happening at all.

Example noted:
I have an issue with team invitation, I can't accept invitation from my team, and I can't join them. I tried to do it via e-mail invitation and therefore directly on the website. Email invitation redirect me to the blurred parabol page, the invitation from the notification on the parabol page does not work at all.

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Fixes #10085 

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Step 1
  - Step 2...

- [ ] Scenario B
  - Step 1
  - Step 2....

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label https://github.com/ParabolInc/parabol/labels/Skip%20Maintainer%20Review if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

File: packages/server/graphql/mutations/helpers/bootstrapNewUser.ts [hunk 1]
```diff
@@ -110,11 +110,20 @@ const bootstrapNewUser = async (
           type: 'inviteYourTeam' as const,
           priority: 2
         }
+        // We're racing with accept team invitation here which also adds some suggested actions. We don't want this to fail just because of duplicates.
```
Comment (Dschoordsch) [inline packages/server/graphql/mutations/helpers/bootstrapNewUser.ts:113]: While this is true, the more common case where the bug occurs is bootstrap without autojoin which adds the `createNewTeam` suggested action which then is also added in `acceptTeamInvitation`.

**Comment by Dschoordsch** [comment]
This was introduced in #10035

**Comment by Dschoordsch** [comment]
This is not very elegant but recreates the behaviour we had with rethink before. Because this affects a lot of users, I'm going to merge as is and we can clean it up later if we want.
