### PR TITLE
fix: types in meeting tips; prevent rendering undefined

### LINKED ISSUE #8442: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for com...
Affected > 150 users and happened > 200 times

https://parabol.sentry.io/issues/4254783524/?referrer=github_plugin

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
  at Vg (./node_modules/react-dom/cjs/react-dom.production.min.js:280:177)
  at Zg (./node_modules/react-dom/cjs/react-dom.production.min.js:149:163)
  at fi (./node_modules/react-dom/cjs/react-dom.production.min.js:176:171)
  at ck (./node_modules/react-dom/cjs/react-dom.production.min.js:271:134)
  at bk (./node_modules/react-dom/cjs/react-dom.production.min.js:250:347)
...
(10 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by BartoszJarocki**
# Description

Fixes #8442 

## Demo

No demo

## Testing scenarios

- [ ] Go to the team health check and see if there's an error thrown about rendering `undefined`

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by BartoszJarocki** [comment]
@nickoferrall i'm assigning you as its team health check related. i would appreciate if you could take a look, thanks!

File: packages/client/components/BottomControlBarTips.tsx [hunk 1]
```diff
@@ -80,15 +80,25 @@ const EstimateHelpMenu = lazyPreload(
...
-const demoHelps = {
+const demoHelps: Record<NewMeetingPhaseTypeEnum, LazyExoticPreload<any> | null> = {
   checkin: DemoReflectHelpMenu,
   reflect: DemoReflectHelpMenu,
   group: DemoGroupHelpMenu,
   vote: DemoVoteHelpMenu,
-  discuss: DemoDiscussHelpMenu
-} as Record<NewMeetingPhaseTypeEnum, LazyExoticPreload<any>>
+  discuss: DemoDiscussHelpMenu,
+  ESTIMATE: null,
```
Comment (Dschoordsch) [inline packages/client/components/BottomControlBarTips.tsx:89]: +1 You could type it as `Partial<Record<...>>` to avoid having to specify all the empty values.

Comment (BartoszJarocki) [reply packages/client/components/BottomControlBarTips.tsx:89]: yeah, but his way it's will scream if a new phase is added and not handled here, which is good, imo

File: packages/client/components/BottomControlBarTips.tsx [hunk 2]
```diff
@@ -80,15 +80,25 @@ const EstimateHelpMenu = lazyPreload(
...
 )
 
-const demoHelps = {
+const demoHelps: Record<NewMeetingPhaseTypeEnum, LazyExoticPreload<any> | null> = {
   checkin: DemoReflectHelpMenu,
   reflect: DemoReflectHelpMenu,
   group: DemoGroupHelpMenu,
   vote: DemoVoteHelpMenu,
-  discuss: DemoDiscussHelpMenu
-} as Record<NewMeetingPhaseTypeEnum, LazyExoticPreload<any>>
```
[the remark this answers is not in the document]
Comment (BartoszJarocki) [reply packages/client/components/BottomControlBarTips.tsx:89]: me neither, but I really want to use it 😅

File: packages/client/components/BottomControlBarTips.tsx (hunk 1 above)
Comment (BartoszJarocki) [reply packages/client/components/BottomControlBarTips.tsx:89]: @Dschoordsch after giving it a second thought, you're right. i thought it'd be a good reminder to add/not add a tooltip but this should be considered on the design phase, not enforced by TS. will change.

**Comment by nickoferrall** [comment]
> @nickoferrall i'm assigning you as its team health check related. i would appreciate if you could take a look, thanks!

@Dschoordsch built the team health check feature, but I'm happy to review this if you like?

**Comment by BartoszJarocki** [comment]
@nickoferrall let's redirect it to @Dschoordsch then. @Dschoordsch do you mind taking a final look?

**Review by Dschoordsch — APPROVED** [review]
