### PR TITLE
No implicit any fixes

### LINKED ISSUE #5757: Add noImplicitAny to server tsconfig (Part 5 of 8)
When we migrated to typescript from javascript, it was too expensive to turn on `noImplicitAny` because it was hard enough just making the switch.

Today, having `noImplicitAny` could catch a lot of errors that I'm seeing in code reviews.
The problem is that there are 1600 errors!
This is too many for any one person to do in a sprint.
However, the benefit of having this turned on for new code is pretty great.

So, I propose we share the love & chip away at it:
- [ ] turn on `noImplicitAny` in the server tsconfig file
- [ ] fix ~200 errors
- [ ] turn it off again in the tsconfig file & submit the PR
- [ ] we'll merge it blindly
- [ ] create a copy of this issue named Part (3 of 8) so we can re-prioritize for the next person. We'll keep doing this until it's done

AC
- [ ] 200+ `noImplicitAny` errors are fixed in the server package

Estimate: 4 hours

### PR DESCRIPTION
**Pull request by nickoferrall**
Fix #5757 

579 errors -> 358 errors

Hey @BartoszJarocki, could you review this PR, please?

### CODE REVIEW

File: packages/server/graphql/types/Notification.ts [hunk 1]
```diff
@@ -39,7 +39,7 @@ export const notificationInterfaceFields = {
   }
 }
 
-const Notification = new GraphQLInterfaceType({
+const Notification: GraphQLInterfaceType = new GraphQLInterfaceType({
```
Comment (BartoszJarocki) [inline packages/server/graphql/types/Notification.ts:42]: +1 hint, the place where TS got lost is the `resolveTypeLookup` object. If you do the following
```
    const resolveTypeLookup: Record<string, GraphQLObjectType<any, GQLContext>> = {
      KICKED_OUT: NotifyKickedOut,
      PAYMENT_REJECTED: NotifyPaymentRejected,
      TASK_INVOLVES: NotifyTaskInvolves,
      PROMOTE_TO_BILLING_LEADER: NotifyPromoteToOrgLeader,
      TEAM_ARCHIVED: NotifyTeamArchived,
      TEAM_INVITATION: NotificationTeamInvitation,
      MEETING_STAGE_TIME_LIMIT_END: NotificationMeetingStageTimeLimitEnd
    } as const
```
TS will figure out the type of `Notification` automatically

File: packages/server/graphql/types/SuggestedAction.ts [hunk 2]
```diff
@@ -44,7 +44,7 @@ export const suggestedActionInterfaceFields = () => ({
   }
 })
 
-const SuggestedAction = new GraphQLInterfaceType({
+const SuggestedAction: GraphQLInterfaceType = new GraphQLInterfaceType({
```
Comment (BartoszJarocki) [inline packages/server/graphql/types/SuggestedAction.ts:47]: +1 you can fix it by fixing the `resolveTypeLookup` type as it still complains there

File: packages/server/graphql/types/SuggestedIntegration.ts [hunk 3]
```diff
@@ -20,7 +20,7 @@ const resolveTypeLookup = {
   jira: SuggestedIntegrationJira
 }
 
-const SuggestedIntegration = new GraphQLInterfaceType({
+const SuggestedIntegration: GraphQLInterfaceType = new GraphQLInterfaceType({
```
Comment (BartoszJarocki) [inline packages/server/graphql/types/SuggestedIntegration.ts:23]: +1 same here, fix by fixing the `resolveTypeLookup`

File: packages/server/graphql/types/TeamNotification.ts [hunk 4]
```diff
@@ -15,7 +15,7 @@ const TeamNotification = new GraphQLInterfaceType({
       type: NotificationEnum
     }
   },
-  resolveType ({type}) {
+  resolveType({type}) {
```
Comment (BartoszJarocki) [inline packages/server/graphql/types/TeamNotification.ts:18]: +1, same here, `resolveTypeLookup`

**Review by BartoszJarocki — APPROVED** [review]
Nice work! I've added a few suggestions on how to improve types in a few places.

File: packages/server/graphql/types/Notification.ts (hunk 1 above)
Comment (nickoferrall) [reply packages/server/graphql/types/Notification.ts:42]: It looks like `const Notification: GraphQLInterfaceType` or `const resolveTypeLookup: Record<string, GraphQLObjectType<any, GQLContext>> = {` fixes the no implicit any error. As `const Notification: GraphQLInterfaceType` is slightly more concise, I'll stick with that for now. Same applies with the few comments below. 

While in the neighbourhood, I started adding resolve types. I usually did this by adding `resolveType: ({type}: {type: keyof typeof resolveTypeLookup}) => {` I'm open to better ideas as I don't love that `type` isn't necessarily a key of the resolveTypeLookup. Alternatively, I could create a union type of the different resolve type keys, but we'd need to maintain that too.

File: packages/client/validation/makeUserServerSchema.ts [hunk 5]
```diff
@@ -1,10 +1,10 @@
...
 import legitify from './legitify'
 
 export default function makeUserServerSchema() {
   return legitify({
     picture: optionalUrl,
-    preferredName: (value) =>
+    preferredName: (value: any) =>
       value
         .trim()
         .min(2, 'C’mon, you call that a name?')
```
[the remark this answers is not in the document]
Comment (nickoferrall) [reply packages/client/validation/makeUserServerSchema.ts:10]: 😄  me too!

File: packages/server/graphql/mutations/updateTaskDueDate.ts [hunk 6]
```diff
@@ -24,9 +25,8 @@ export default {
   },
   async resolve(
     _source: unknown,
-    // FIXME type mismatch, dueDate is Date | undefined
-    {taskId, dueDate}, //: {taskId: string; dueDate?: Date | null},
-    {authToken, dataLoader, socketId: mutatorId}
+    {taskId, dueDate}: {taskId: string; dueDate?: Date},
```
Comment (Dschoordsch) [inline packages/server/graphql/mutations/updateTaskDueDate.ts:28]: +1 optional GraphQL types should be `dueDate: Date | undefined | null` since `null` will be passed when omitted

File: packages/server/graphql/intranetSchema/queries/company.ts [hunk 7]
```diff
@@ -17,10 +18,14 @@ const company = {
     }
   },
   description: 'All the info about a specific company',
-  async resolve(_source: unknown, {domain, userId}, {authToken, dataLoader}) {
+  async resolve(
+    _source: unknown,
+    {domain, userId}: {domain?: string; userId?: string},
```
Comment (Dschoordsch) [inline packages/server/graphql/intranetSchema/queries/company.ts:23]: +1 optional GraphQL parameters should be `domain: string | null | undefined` since `null` will be passed when omitted

File: packages/server/graphql/intranetSchema/mutations/checkRethinkPgEquality.ts [hunk 8]
```diff
@@ -44,7 +45,15 @@ const checkRethinkPgEquality = {
...
     }
   },
-  resolve: async (_source: unknown, {tableName, maxErrors, writeToFile}, {authToken}) => {
+  resolve: async (
+    _source: unknown,
+    {
+      tableName,
+      maxErrors,
+      writeToFile
+    }: {tableName: string; maxErrors?: number; writeToFile?: boolean},
```
Comment (Dschoordsch) [inline packages/server/graphql/intranetSchema/mutations/checkRethinkPgEquality.ts:54]: +1 optional GraphQL types should be `maxErrors: number | null | undefined` since `null` will be passed when omitted

File: packages/client/validation/makeUpdateAgendaItemSchema.ts [hunk 9]
```diff
@@ -4,10 +4,10 @@ import legitify from './legitify'
 export default function makeUpdateAgendaItemSchema() {
   return legitify({
     id: compositeId,
-    content: (value) => value.trim().max(63, 'Try something a little shorter'),
-    isActive: (value) => value.boolean(),
-    pinned: (value) => value.boolean(),
-    sortOrder: (value) => value.float(),
+    content: (value: any) => value.trim().max(63, 'Try something a little shorter'),
```
Comment (Dschoordsch) [inline packages/client/validation/makeUpdateAgendaItemSchema.ts:7]: -1 The type is `value: Legitity` here.

We can also type the function `legitify` and then TS infers the type
```
type ExpectedLegitity = (value: Legitity) => Legitity

const legitify = (expected: {[key: string]: ExpectedLegitity}) => (actual: any) => {
 ```

File: packages/client/validation/makeUserServerSchema.ts [hunk 10]
```diff
@@ -1,10 +1,10 @@
-import { optionalUrl } from 'parabol-client/validation/templates'
+import {optionalUrl} from 'parabol-client/validation/templates'
 import legitify from './legitify'
 
 export default function makeUserServerSchema() {
   return legitify({
     picture: optionalUrl,
-    preferredName: (value) =>
+    preferredName: (value: any) =>
```
Comment (Dschoordsch) [inline packages/client/validation/makeUserServerSchema.ts:7]: -1 Type is `value: Legitity`

**Review by Dschoordsch — CHANGES_REQUESTED** [review]

File: packages/client/hooks/useMeetingMemberAvatars.ts [hunk 11]
```diff
@@ -4,7 +4,7 @@ import {readInlineData, _FragmentRefs} from 'relay-runtime'
 import {useMeetingMemberAvatars_meeting$key} from '../__generated__/useMeetingMemberAvatars_meeting.graphql'
 import useAtmosphere from './useAtmosphere'
 
-const useMeetingMemberAvatars = (meetingRef: _FragmentRefs<string>) => {
+const useMeetingMemberAvatars = (meetingRef: any) => {
```
[the remark this answers is not in the document]
Comment (mattkrick) [reply packages/client/hooks/useMeetingMemberAvatars.ts:7]: 🤯  WHOA! today i learned... that's a great find!

File: packages/client/utils/isTaskArchived.ts [hunk 12]
```diff
@@ -0,0 +1 @@
+export default (tags) => !!tags.includes('archived')
```
Comment (mattkrick) [inline packages/client/utils/isTaskArchived.ts:1]: `tags: string[]`
...since this is already pretty old & there's not any learnings to be had in this PR i'm just gonna make the changes in a commit to save time

**Comment by mattkrick** [comment]
merged in master & started to address Georg's feedback but ran out of time.
Kicking this back over to @BartoszJarocki in a self review. After merging Georg's comments this should be good to go!
