### PR TITLE
fix: use radix-ui for avatars

### LINKED ISSUE #9632: Persisted avatar on meeting header of solo updates
Screenshot 2024-04-11 at 8 12 23 AM

Repro:
- start a meeting with 2+ people
- move from person 1 to person 2 and notice on person 2's update stage the avatar still shows person 1

### PR DESCRIPTION
**Pull request by mattkrick**
# Description

fixes #9632 

I broke the avatars trying to do a cheap fix. The right way to load fallbacks is using radix-ui, which has that functionality built into it + a ton of accessibility things, so this PR refactors all avatars to use radix-ui + tailwinds.

This also fixes some really ugly avatar related stuff like below

Screenshot 2024-04-11 at 11 34 45 AM
Screenshot 2024-04-11 at 11 34 18 AM

### CODE REVIEW

File: packages/client/components/TopBarAvatar.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ const AvatarWrapper = styled('button')({
   borderRadius: 100,
   marginLeft: 8,
   padding: 4,
-  ':focus': {
+  ':focus-visible': {
```
Comment (mattkrick) [inline packages/client/components/TopBarAvatar.tsx:19]: i hate when the accessibility blue outline shows up when you click! it should show up when you tab, not click.
