### PR TITLE
fix: fix check-in discussion panel layout

### LINKED ISSUE #8922: Discussion panel layout broken when it has no comments
See the screenshot

image

AC:
- discussion panel works correctly in an empty state

### PR DESCRIPTION
**Pull request by igorlesnenko**
fix #8922
image

How to test:
- See that in check-in, retro and other meeting types the panel works as expected
- See that zoom functionality still works as expected

### CODE REVIEW

File: packages/client/components/DiscussionThreadListEmptyState.tsx [hunk 1]
```diff
@@ -132,14 +132,14 @@ const DiscussionThreadListEmptyState = (props: Props) => {
       }
     }
   })
-  if (!meeting) return null
```
Comment (igorlesnenko) [inline packages/client/components/DiscussionThreadListEmptyState.tsx:135]: The issue is that this component is not used only in retro meetings, so if meeting is not retro we don't show beautiful empty state at all

**Comment by rafaelromcar-parabol** [comment]
@mattkrick

**Review by jmtaber129 — APPROVED** [review]

**Comment by ackernaut** [comment]
Thanks for the fix!
