### PR TITLE
Hotfix - Can create new teams

### LINKED ISSUE #5721: Invitation required screen right after creating a new team
## Issue - Bug

**How to reproduce**

- Create a new team in existing organisation
- See the new team board is opened
- Refresh a page
- See "Invitation required" screen
- See you are no longer able to access the team

image

**Another way to reproduce:**

- Create a new organisation, specify team name
- Refresh the page, see organisation disappeared from the sidebar
- Refresh the page again — it appeared in the sidebar
- Refresh again — disappeared, etc.
- Wait for several minutes
- Refresh the page — see invitation required screen
- Try to click on it in the sidebar — invitation required screen, you are no longer able to access the organisation

https://user-images.githubusercontent.com/466991/143608984-d331a1e3-0045-476a-a7cf-385fb245fb62.mov

### PR DESCRIPTION
**Pull request by mattkrick**
Fix #5721

Caching the User objects in redis is hurting us again, so this PR rips out all User object caching.
Instead of using a permanent cache, this PR uses a dataloader if possible, or goes out to PG if a dataloader isn't easy to access.

This also fixes that pesky husky bug that just started appearing on my machine this morning.

TEST

- [ ] can create a new team & refresh the page & still be on that team page
- [ ] can archive a team
- [ ] can create a new user

### CODE REVIEW

File: packages/server/graphql/intranetSchema/mutations/sendUpcomingInvoiceEmails.ts [hunk 1]
```diff
@@ -113,7 +113,9 @@ const sendUpcomingInvoiceEmails = {
       (prev, cur) => prev.concat(cur.billingLeaderIds, cur.newUserIds),
       [] as string[]
     )
-    const allUsers = await getUsersByIds(allUserIds)
+    const allUsers = await Promise.all(
+      allUserIds.map((userId) => dataLoader.get('users').load(userId))
+    )
```
Comment (tianrunhe) [inline packages/server/graphql/intranetSchema/mutations/sendUpcomingInvoiceEmails.ts:118]: why not `const allUsers = await dataLoader.get('users').loadMany(allUserIds)`?

File: packages/server/safeMutations/safeArchiveTeam.ts [hunk 2]
```diff
@@ -1,27 +1,23 @@
...
-      tms: user('tms').difference([teamId])
-    })),
-    removeUserTms(teamId, userIds)
-  ])
+  await removeUserTms(teamId, userIds)
   const updates = {
     isArchived: true,
     updatedAt: new Date()
   }
+  const users = await Promise.all(userIds.map((userId) => dataLoader.get('users').load(userId)))
```
Comment (tianrunhe) [inline packages/server/safeMutations/safeArchiveTeam.ts:20]: Why not `loadMany(userIds)`?

File: packages/server/graphql/mutations/helpers/removeTeamMember.ts [hunk 3]
```diff
@@ -116,18 +115,10 @@ const removeTeamMember = async (
       .default([]) as unknown) as Task[]
   }).run()
 
-  const reqlUpdater = (user) => ({
-    tms: user('tms').difference([teamId])
-  })
+  await removeUserTms(teamId, userId)
+  const user = await dataLoader.get('users').load(userId)
```
Comment (tianrunhe) [inline packages/server/graphql/mutations/helpers/removeTeamMember.ts:119]: Can put in `Promise.all()`?

**Review by tianrunhe — APPROVED** [review]
LGTM! I run the entire release test suites just to make sure everything works.

File: packages/server/graphql/isValid.ts [hunk 4]
```diff
@@ -0,0 +1,5 @@
+// this is useful anytime you call `loadMany` on a dataloader
+const isValid = <T>(obj: T | Error | undefined | null): obj is T => {
```
Comment (BartoszJarocki) [inline packages/server/graphql/isValid.ts:2]: nit - we put that kind of predicates in different directories and it's hard to find them, maybe we should put everything In `utils/predicates` file? or if we want to have a separate file per predicate `utils/predicates`?

**Review by BartoszJarocki — APPROVED** [review]
I couldn't reproduce the original issue on local env but this PR doesn't break anything. Nice work!

File: packages/server/graphql/intranetSchema/mutations/sendUpcomingInvoiceEmails.ts (hunk 1 above)
Comment (Dschoordsch) [reply packages/server/graphql/intranetSchema/mutations/sendUpcomingInvoiceEmails.ts:118]: `loadMany` returns `(IUser | Error)[]` and needs additional filtering/throwing, while `Promise.all(...load(...))` returns `IUser[]` and throws if there is an issue. Otherwise these are identical since `loadMany` does internally just `Promise.all(...load(...))`.

**Comment by nickoferrall** [comment]
Just linking this GitHub issue to this Sentry issue so that we can close the Sentry issue.

Sentry issue: [ACTION-PRODUCTION-9RX](https://sentry.io/organizations/parabol/issues/2682538363/?referrer=github_plugin)
