### PR TITLE
fix: ensure process recurrence runs sequentially

### LINKED ISSUE #11261: Bug: processRecurrence creates multiple meeting end events if ran in parallel multiple times
There is a race condition when `processRecurrence` is ran multiple times at the same time, like it can easily happen with chronos integrated in the server.
This happens because we load all meetings to end at the very start of the mutation and then batch processing all of them.
See also this [Slack thread](https://parabol.slack.com/archives/C4JAUUZ9P/p1745424131286779) 🔒 

`processRecurrence` should lock itself agains being run in parallel.

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Fixes #11261 
Wrap the resolver in a lock function which returns an error if it's already running somewhere.

## Demo

```
3:21:00 2|Socket Server                  | {"time":"2025-04-30T11:21:00.014Z","level":"info","message":"🌱 Chronos Job processRecurrence: TICK []"}
13:21:00 4|Socket Server                  | {"time":"2025-04-30T11:21:00.016Z","level":"info","message":"🌱 Chronos Job processRecurrence: TICK []"}
13:21:00 1|Socket Server                  | {"time":"2025-04-30T11:21:00.017Z","level":"info","message":"🌱 Chronos Job processRecurrence: TICK []"}
13:21:00 1|Socket Server                  | Attempting to acquire lock for processRecurrence
13:21:00 8|Socket Server                  | {"time":"2025-04-30T11:21:00.021Z","level":"info","message":"🌱 Chronos Job processRecurrence: TICK []"}
13:21:00 1|Socket Server                  | Lock acquired for processRecurrence
13:21:00 2|Socket Server                  | Attempting to acquire lock for processRecurrence
13:21:00 4|Socket Server                  | Attempting to acquire lock for processRecurrence
13:21:00 8|Socket Server                  | Attempting to acquire lock for processRecurrence
13:21:00 8|Socket Server                  | {"time":"2025-04-30T11:21:00.063Z","level":"info","message":"SEND TO SENTRY [\n  Error: Mutation processRecurrence is already running\n      at /Volumes/User/parabol/dev/web.js:19999:49\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Object.processRecurrence (/Volumes/User/parabol/dev/web.js:75:14)\n      at async callGQL (/Volumes/User/parabol/dev/web.js:71603:18),\n  { tags: undefined }\n]"}
13:21:00 2|Socket Server                  | {"time":"2025-04-30T11:21:00.063Z","level":"info","message":"SEND TO SENTRY [\n  Error: Mutation processRecurrence is already running\n      at /Volumes/User/parabol/dev/web.js:19999:49\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Object.processRecurrence (/Volumes/User/parabol/dev/web.js:75:14)\n      at async callGQL (/Volumes/User/parabol/dev/web.js:71603:18),\n  { tags: undefined }\n]"}
13:21:00 4|Socket Server                  | {"time":"2025-04-30T11:21:00.067Z","level":"info","message":"SEND TO SENTRY [\n  Error: Mutation processRecurrence is already running\n      at /Volumes/User/parabol/dev/web.js:19999:49\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Object.processRecurrence (/Volumes/User/parabol/dev/web.js:75:14)\n      at async callGQL (/Volumes/User/parabol/dev/web.js:71603:18),\n  { tags: undefined }\n]"}
```

## Testing scenarios

* same preparations as #11272 
* comment out the lock in https://github.com/ParabolInc/parabol/blob/2dcdb0f0dfbc2e88d26eec53f85d6c8f337d058a/packages/server/LeaderRunner.ts#L22
* see multiple simultaneous ticks of `processRecurrence` with n-1 reporting a standard error

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label https://github.com/ParabolInc/parabol/labels/Skip%20Maintainer%20Review if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

File: packages/server/graphql/private/mutations/processRecurrence.ts [hunk 1]
```diff
@@ -105,108 +106,106 @@ const startRecurringMeeting = async (
...
-          return safeEndTeamPrompt({meeting, context, subOptions})
-        } else if (meeting.meetingType === 'retrospective') {
-          return safeEndRetrospective({meeting, now, context})
-        } else {
-          return standardError(new Error('Unhandled recurring meeting type'), {
-            tags: {meetingId: meeting.id, meetingType: meeting.meetingType}
-          })
-        }
-      })
+const processRecurrence: MutationResolvers['processRecurrence'] = checkSequential(
```
Comment (Dschoordsch) [inline packages/server/graphql/private/mutations/processRecurrence.ts:109]: Only this line changed, everything else is just indentation.
