### PR TITLE
chore(noImplicitAny): fix more errors

### LINKED ISSUE #5831: Add noImplicitAny to server tsconfig (Part 6 of 8)
When we migrated to typescript from javascript, it was too expensive to turn on `noImplicitAny` because it was hard enough just making the switch.

Today, having `noImplicitAny` could catch a lot of errors that I'm seeing in code reviews.
The problem is that there are 1600 errors!
This is too many for any one person to do in a sprint.
However, the benefit of having this turned on for new code is pretty great.

So, I propose we share the love & chip away at it:
- [ ] turn on `noImplicitAny` in the server tsconfig file
- [ ] fix ~200 errors
- [ ] turn it off again in the tsconfig file & submit the PR
- [ ] we'll merge it blindly
- [ ] create a copy of this issue named Part (3 of 8) so we can re-prioritize for the next person. We'll keep doing this until it's done

AC
- [ ] 200+ `noImplicitAny` errors are fixed in the server package

Estimate: 4 hours

### PR DESCRIPTION
**Pull request by mattkrick**
fix #5831

notes:
- removed stripe.js in favor of the new StripeManager, quicker than writing types for the legacy file

### CODE REVIEW

File: packages/client/modules/demo/handleCompletedDemoStage.ts [hunk 1]
```diff
@@ -61,9 +61,10 @@ const addStageToBotScript = (stageId: string, db: RetroDemoDB, reflectionGroupId
         }))
       )
     }
-    const comment = commentLookup[reflection.id]
-    if (comment) {
-      comments.push(comment)
+    const comment = commentLookup[reflection.id as keyof typeof commentLookup]
+    if (Array.isArray(comment)) {
+      // I think this was a bug before...
```
Comment (mattkrick) [inline packages/client/modules/demo/handleCompletedDemoStage.ts:66]: noImplicitAny caught a bug here

File: packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx [hunk 2]
```diff
@@ -1,5 +1,6 @@
 import graphql from 'babel-plugin-relay/macro'
-import Parser from 'json2csv/lib/JSON2CSVParser' // only grab the sync parser
+import type {Parser as JSON2CSVParser} from 'json2csv'
```
Comment (mattkrick) [inline packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx:2]: i don't usually import type, but i wanted to be sure we aren't imported the whole package because it's a big one

File: packages/client/types/constEnums.ts [hunk 3]
```diff
@@ -307,14 +307,6 @@ export const enum SubscriptionChannel {
   ORGANIZATION = 'organization'
 }
 
-export const enum SuggestedActionTypeEnum {
```
Comment (mattkrick) [inline packages/client/types/constEnums.ts:310]: we now have a single source of truth for these in the graphql enum

File: packages/server/database/migrations/20161125141100-addOrgs.js [hunk 4]
```diff
@@ -119,21 +118,23 @@ exports.up = async (r) => {
...
-        metadata: customer.metadata,
-        plan: 'parabol-pro-monthly',
-        quantity: Object.keys(orgs[customer.metadata.orgId].orgUserMap).length,
-        trial_period_days: TRIAL_PERIOD_DAYS
-      })
-    })
-  )
+  // turned into a noop to remove dependency on stripe
+  const subscriptions = []
+  // const orgIds = Object.keys(orgs)
```
Comment (mattkrick) [inline packages/server/database/migrations/20161125141100-addOrgs.js:123]: deleted the stripe helper, which this depends on, so had to remove any logic using it.
in the future, we shouldn't do stripe things in migrations, but this was 6 years ago

File: packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/MeetingMembersWithoutTasks.tsx [hunk 5]
```diff
@@ -18,9 +17,9 @@ const headerStyle = {
   paddingTop: 24
 }
 
-const getHeaderText = (meetingType) => {
+const getHeaderText = (meetingType: 'retrospective' | 'action' | 'poker') => {
```
Comment (JimmyLv) [inline packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/MeetingMembersWithoutTasks.tsx:20]: shall we use the same way as `TSuggestedActionTypeEnum`, to use the `MeetingTypeEnum` type extracted from `GraphQLEnumType`?

File: packages/client/types/constEnums.ts (hunk 3 above)
Comment (JimmyLv) [reply packages/client/types/constEnums.ts:310]: yeah, single source of truth! the `keyof typeof` is really helpful when doing TypeScript legacy support.
btw: have we tried any migration tool like [ts-migrate](https://github.com/airbnb/ts-migrate) before? I'm curious about how it will actually work.

File: packages/client/utils/date/relativeDate.ts [hunk 6]
```diff
@@ -52,16 +52,16 @@ const relativeDate = (date: string | Date, opts: Opts = {}) => {
     day: (abs % MONTH) / DAY,
     hour: (abs % DAY) / HOUR,
     minute: (abs % HOUR) / MIN
-  }
+  } as const
 
-  let k
-  let val
+  let k: any
+  let val: any
```
Comment (nickoferrall) [inline packages/client/utils/date/relativeDate.ts:58]: +1 would `k` and `val` both be `number | string`?

File: packages/server/graphql/queries/helpers/makeUpcomingInvoice.ts [hunk 7]
```diff
@@ -22,10 +22,10 @@ export default async function makeUpcomingInvoice(
     amountDue: stripeInvoice.amount_due,
     total: stripeInvoice.total,
     endAt: fromEpochSeconds(stripeInvoice.period_end),
-    invoiceDate: fromEpochSeconds(stripeInvoice.date),
+    invoiceDate: fromEpochSeconds(stripeInvoice.date!),
     orgId,
     startAt: fromEpochSeconds(stripeInvoice.period_start),
-    startingBalance: stripeInvoice.startingBalance,
+    startingBalance: stripeInvoice.starting_balance,
```
Comment (nickoferrall) [inline packages/server/graphql/queries/helpers/makeUpcomingInvoice.ts:28]: +2 TypeScript FTW 🎉

File: packages/server/graphql/types/AtlassianIntegration.ts [hunk 8]
```diff
@@ -102,11 +107,8 @@ const AtlassianIntegration = new GraphQLObjectType<any, GQLContext>({
             'A list of projects to restrict the search to. format is cloudId:projectKey. If null, will search all'
         }
       },
-      resolve: async (
-        {teamId, userId, accessToken, cloudIds}: AtlassianAuth,
-        {first, queryString, isJQL, projectKeyFilters},
-        {authToken}: GQLContext
-      ) => {
+      resolve: async ({teamId, userId, accessToken, cloudIds}, args: any, {authToken}) => {
```
Comment (nickoferrall) [inline packages/server/graphql/types/AtlassianIntegration.ts:110]: I was wondering why you didn't do `args: IssueArgs` and remove the casting below, but I see it makes the `field` type incompatible. Annoying that you can't define the args type in a `GraphQLObjectType`

**Review by nickoferrall — APPROVED** [review]
LGTM!

File: packages/client/modules/demo/handleCompletedDemoStage.ts (hunk 1 above)
Comment (mattkrick) [reply packages/client/modules/demo/handleCompletedDemoStage.ts:66]: all the values in `commentLookup` are arrays. perhaps that was an error? i didn't want to change that though

File: packages/client/types/constEnums.ts (hunk 3 above)
Comment (mattkrick) [reply packages/client/types/constEnums.ts:310]: the last time i checked it out it was still a little buggy & at best it would just explicitly cast things as `any` as a fallback.
this little exercise probably took the team 30-40 hours to complete, but we uncovered some cool bugs & got some really useful patterns (like keyof typeof) in place so future developers have some good patterns to go off of.

File: packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/MeetingMembersWithoutTasks.tsx (hunk 5 above)
Comment (mattkrick) [reply packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/MeetingMembersWithoutTasks.tsx:20]: yep! the relay-compiler gives us those enums in the generated files so we don't have to reference the server from the client so I'll just pull from there.

```ts
import {
  MeetingMembersWithoutTasks_meeting,
  MeetingTypeEnum
} from 'parabol-client/__generated__/MeetingMembersWithoutTasks_meeting.graphql'
```

File: packages/client/modules/email/components/EmailBlock/EmailBlock.tsx [hunk 9]
```diff
@@ -26,7 +26,7 @@ const innerStyle = {
   width: '100%'
 } as const
 
-const EmailBlock = (props) => {
+const EmailBlock = (props: any) => {
```
[the remark this answers is not in the document]
Comment (mattkrick) [reply packages/client/modules/email/components/EmailBlock/EmailBlock.tsx:29]: this component is HTML4 😨  
that's the only way to write components so they work in email
