### PR TITLE
fix: fix the issue where a successful upgrade won't refresh the billing page

### LINKED ISSUE #9737: Bug: successful upgrade does not refresh the billing page
> One thing I noticed, also on master: when upgrading, I see the fireworks, but the buttons stays in the loading state "upgrading..." and I have to refresh the page to see the new invoice and setting. Do we already have an issue for this?

_Originally posted by @Dschoordsch in https://github.com/ParabolInc/parabol/pull/9727#pullrequestreview-2044969298_

### PR DESCRIPTION
**Pull request by tianrunhe**
# Description

Fixes #9737 

## Demo
Stripe webhooks are slow locally. Please be patient while viewing this GIF😂:

## Testing scenarios

- [ ] Upgrade to `team`
  - Upgrade an org to `team` tier
  - ~Brew a cup of coffee and wait~
  - Observe the billing page refreshes itself and the confetti shows up eventually

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label https://github.com/ParabolInc/parabol/labels/Skip%20Maintainer%20Review if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

File: packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx [hunk 1]
```diff
@@ -125,12 +126,20 @@ const BillingForm = (props: Props) => {
...
         return
       }
+      if (paymentIntent.status === 'succeeded') {
+        commitLocalUpdate(atmosphere, (store) => {
+          const organization = store.get(orgId)
+          if (!organization) return
+          organization.setValue('team', 'billingTier')
+          organization.setValue('team', 'tier')
+        })
+      }
```
Comment (Dschoordsch) [inline packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx:142]: -1 let's put this logic in the `upgradeToTeamTierSuccessUpdater` where we also open the drawer and show the confetti

**Review by Dschoordsch — CHANGES_REQUESTED** [review]

**Review by Dschoordsch — APPROVED** [review]
For me it's missing the 2 topmost sections ("Invoices" and "Credit card") after the upgrade without a manual refresh, but it's already an improvement to the state before.

**Comment by tianrunhe** [comment]
> For me it's missing the 2 topmost sections ("Invoices" and "Credit card") after the upgrade without a manual refresh, but it's already an improvement to the state before.

The invoices section is a bit tricky: we need to wait for Stripe to finalize the paid invoice & create the upcoming invoice to have the data to populate that vie but those happen a little bit later than the payment success. To give the customer a faster turnaround & an indicator they have successfully upgraded, I think this is fine for now.
