### PR TITLE
Fix remotely ungrouped results position in Spotlight

### LINKED ISSUE #5627: Spotlight: remotely ungrouping result group bug
A reflection doesn't return to the correct position in the Spotlight modal if it's remotely ungrouped in the results section.

To reproduce:
- Alice opens the Spotlight in client A. One of the result groups contains 2 reflections
- Bob, in client B, ungroups the result group that contains 2 reflections
- Alice sees that the reflection returns to the incorrect position in the result groups

### AC

- [ ] If a results reflection group is remotely ungrouped, it returns to the expected position in the Spotlight

### PR DESCRIPTION
**Pull request by nickoferrall**
Fix #5627 

### To test

- [ ] If Alice remotely ungroups a result group, Bob sees the ungrouped reflection move into the expected position in the Spotlight modal
- [ ] If a remote reflection is dropping and the viewer opens the Spotlight, the dropping remote reflection does not move into the Spotlight (see gif example here https://github.com/ParabolInc/parabol/issues/5415#issuecomment-937912945)

### CODE REVIEW

File: packages/client/components/ReflectionGroup/DraggableReflectionCard.tsx [hunk 1]
```diff
@@ -112,28 +114,17 @@ const DraggableReflectionCard = (props: Props) => {
...
-        }
-        // if the spotlight is closed, this card is the single source of truth
+        // If the spotlight is closed, this card is the single source of truth
         // Else, if it's a remote drag that is not in the spotlight
         // Else, if this is the instance in the source or search results
+        // And Spotlight modal isn't entering. This throws off dropping remote card position
         const isPriorityCard =
-          !isSpotlightOpen || (!isReflectionIdInSpotlight && remoteDrag) || isInSpotlight
+          (!isSpotlightOpen || (!isReflectionIdInSpotlight && remoteDrag) || isInSpotlight) &&
+          !isSpotlightEntering
```
Comment (nickoferrall) [inline packages/client/components/ReflectionGroup/DraggableReflectionCard.tsx:127]: I don't love passing an extra prop down through a few components, but `isSpotlightEntering` is descriptive, it means we can remove the `useEffect` logic above, and it fixes the two tricky bugs mentioned in the PR description

**Comment by nickoferrall** [comment]
Hey @BartoszJarocki, in the unlikely event you have time left in your workday, would you mind reviewing this PR? No worries if not - I'll tag someone else in tomorrow

**Comment by BartoszJarocki** [comment]
I'm doing it now!

**Review by BartoszJarocki — APPROVED** [review]
@nickoferrall works perfectly! Even though I agree, the props drilling is pretty bad, it's verbose what it's doing so I'd be all for simplifying the logic. Thank finding the solution so quickly, I owe you! 😁
