### PR TITLE
fix: turn on noImplicitAny for server

### LINKED ISSUE #6162: Add noImplicitAny
When we migrated to typescript from javascript, it was too expensive to turn on `noImplicitAny` because it was hard enough just making the switch.

Today, having `noImplicitAny` could catch a lot of errors that I'm seeing in code reviews.
The problem is that there are 1600 errors!
This is too many for any one person to do in a sprint.
However, the benefit of having this turned on for new code is pretty great.

So, I propose we share the love & chip away at it:
- [ ] turn on `noImplicitAny` in the server tsconfig file
- [ ] fix ~200 errors
- [ ] turn it off again in the tsconfig file & submit the PR
- [ ] we'll merge it blindly
- [ ] create a copy of this issue named Part (8 of 8) so we can re-prioritize for the next person. We'll keep doing this until it's done

AC
- [ ] 200+ `noImplicitAny` errors are fixed in the server package

Estimate: 4 hours

### PR DESCRIPTION
**Pull request by mattkrick**
Signed-off-by: Matt Krick <matt.krick@gmail.com>

# Description

Fixes #6162

No more implicit any in the server!
I tried to avoid changing runtime logic wherever possible
pg migrate uses our tsconfig, which means even though we explicitly ignore typechecking migrations (because the types referenced are probably changed in the migration) we still have to make sure migrations don't have implicitAny

### CODE REVIEW

File: packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterTeamAssigneeMenu.tsx [hunk 1]
```diff
@@ -194,16 +194,15 @@ const TaskFooterTeamAssigneeMenu = (props: Props) => {
           />
         )
       })}
-      {addIntegrationModalPortal(
-        (isGitHubTask || isJiraTask) && (
+      {(isGitHubTask || isJiraTask) &&
```
Comment (mattkrick) [inline packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterTeamAssigneeMenu.tsx:197]: changes runtime logic

File: packages/server/dataloader/foreignKeyLoaderMaker.ts [hunk 2]
```diff
@@ -34,18 +26,20 @@ export function foreignKeyLoaderMaker<
...
   primaryLoaderKey: LoaderName,
   foreignKey: KeyName,
-  fetchFn: (keys: readonly LoaderType<LoaderName>[KeyName][]) => Promise<LoaderType<LoaderName>[]>
+  fetchFn: (
+    keys: readonly LoaderType<LoaderName>[KeyName][]
+  ) => Promise<(LoaderType<LoaderName> & {id: string | number})[]>
 ) {
   type T = LoaderType<LoaderName>
-  type PrimaryKeyT = LoaderKeyType<LoaderName>
+  type PrimaryKeyT = string | number
```
Comment (mattkrick) [inline packages/server/dataloader/foreignKeyLoaderMaker.ts:34]: The runtime logic showed that if an item was non-null, it would have an `id` field.
If that's true, then the id field is always gonna be a number or string

File: packages/server/integrations/jiraServer/JiraServerRestManager.ts [hunk 3]
```diff
@@ -230,7 +230,7 @@ export default class JiraServerRestManager implements TaskIntegrationManager {
       return issueTypes
     }
 
-    const bestIssueType = issueTypes.find((type) => type.name === 'Task') || issueTypes.values[0]
+    const bestIssueType = issueTypes.find((type) => type.name === 'Task') || issueTypes[0]
```
Comment (mattkrick) [inline packages/server/integrations/jiraServer/JiraServerRestManager.ts:233]: caught a bug!

File: packages/server/utils/AzureDevOpsServerManager.ts [hunk 4]
```diff
@@ -109,18 +109,29 @@ export interface WorkItemBatchResponse {
...
+  fields: WorkItemFields
   id: number
   relations: WorkItemRelations[]
   rev: number
   url: string
 }
 
 export interface ReferenceLinks {
-  links: object
+  html?: {
```
Comment (mattkrick) [inline packages/server/utils/AzureDevOpsServerManager.ts:132]: not sure if correct, but this is what the runtime logic said it looked like

**Review by Dschoordsch — APPROVED** [review]

File: packages/server/postgres/migrations/1625576993065_addAtlassianAuthTable.ts [hunk 5]
```diff
@@ -40,7 +39,7 @@ export async function up(): Promise<void> {
 
   const atlassianIntegrations = await r
     .table('AtlassianAuth')
-    .filter((row) => row('accessToken').default(null).ne(null))
+    .filter((row: any) => row('accessToken').default(null).ne(null))
```
[the remark this answers is not in the document]
Comment (mattkrick) [reply packages/server/postgres/migrations/1625576993065_addAtlassianAuthTable.ts:42]: pure laziness. fixed!

File: packages/client/components/DropdownMenuToggle.tsx [hunk 6]
```diff
@@ -28,7 +28,7 @@ interface InputStyleProps {
 const InputBlock = styled('div')<InputStyleProps>(
   ({disabled, size}) => ({
     ...ui.fieldBaseStyles,
-    ...ui.fieldSizeStyles[size],
+    ...ui.fieldSizeStyles[size as keyof typeof ui.fieldSizeStyles],
```
[the remark this answers is not in the document]
Comment (mattkrick) [reply packages/client/components/DropdownMenuToggle.tsx:31]: you're right, but it leaves me confused.
why is using a string to access a constant object OK here? shouldn't size be required to be small, medium, large? if string "foo" got passed in, it would yield undefined...
