### PR TITLE
fix: do not run removeOrgUserTaskUpdater for undefined tasks

### LINKED ISSUE #7381: RemoveOrgUserMutation error
Affected 35 users in the past 21 days

https://sentry.io/organizations/parabol/issues/3667878032/?referrer=github_plugin

```
TypeError: Cannot read properties of undefined (reading 'getValue')
  at apply (./packages/client/mutations/RemoveOrgUserMutation.ts:174:60)
  at Set.forEach (<anonymous>)
  at Set.forEach (<anonymous>)
  at Set.forEach (<anonymous>)
...
(28 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by BartoszJarocki**
# Description

Fixes #7381 

## Demo

No demo

## Testing scenarios

- [ ] User removing during the meeting
 - user A is an org billing leader, user B is a user in the user's A org
 - start a check in meeting
 - from a different browser window, join with user B, set a stage to user's B update
 - as a user A, go to org settings and remove user B from org
 - user B should be redirected to the dashboard

- [ ] User with no tasks removed 
 - user B has no tasks
 - user A is an org billing leader
 - user A removes user B
 - users B app doesn't crash

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

File: packages/client/subscriptions/NotificationSubscription.ts [hunk 1]
```diff
@@ -257,6 +257,8 @@ const NotificationSubscription = (
           break
         case 'UpdateFeatureFlagPayload':
           break
+        case 'AuthTokenPayload':
```
Comment (BartoszJarocki) [inline packages/client/subscriptions/NotificationSubscription.ts:260]: This fixes `NotificationSubscription case fail AuthTokenPayload` error showing in the logs. @mattkrick is there anything specific app should do here? just want to make sure it's not a bug and I'm not silencing it

Comment (mattkrick) [reply packages/client/subscriptions/NotificationSubscription.ts:260]: nope, this is just a reeeeeally old pattern that we haven't replaced yet. all the other subscriptions use a lookup table.

**Comment by jmtaber129** [comment]
@BartoszJarocki could you rebase onto latest master and run through the testing scenarios? This doesn't seem to work if I cherry-pick onto master, though there may be a different bug at play here too

**Comment by BartoszJarocki** [comment]
@jmtaber129 I did the testing and here are the results
1. Removing from org without refreshing (same as user without tasks scenario) - works on my end. is something wrong with that scenario on your end? asking because when relay store is involved there might be some race conditions to fix and I just want to make sure it works/doesn't work for everyone

https://user-images.githubusercontent.com/1017620/225063290-cd79b803-03e4-4ecc-9a91-6c3dc770242d.mp4


2. Removing user during the meeting - indeed broken, will take a look if something has changed here

**Comment by jmtaber129** [comment]
@BartoszJarocki after pulling your rebased branch, now things seem to be working 🤔 Not sure what was going on with my local dev with the cherry-picked diff. LGTM!

**Review by jmtaber129 — APPROVED** [review]

**Comment by BartoszJarocki** [comment]
not sure, but since there's no harm in merging that, let's do it! thank you for the review 😄
