### PR TITLE
fix: leader election on interval

### LINKED ISSUE #11262: Bug: establishPrimaryServer does not support restarts of servers
`establishPrimaryServer` only checks for other instances within a startup window of currently `30s`. If a server is restarted after that, then it will assume it's the primary server although the primary one might still be running.

### PR DESCRIPTION
**Pull request by mattkrick**
# Description

fix #11262

chronos wasn't supporting all the server restarts we've been going through.
now, every 3 seconds each server tries to become leader.
the server that wins holds onto it for 20 seconds.
every 10 seconds it renews that election for another 20.
if it can't extend its election for some reason, it stops all its cronjobs & lets someone else become leader.
if it crashes abruptly, its election will last at most 23 seconds (20 seconds for the election TTL + 3 seconds on retry), but on average half that.
when the server receives SIGTERM, it stops trying to become the leader (or releases its leadership, if it is the leader)

### CODE REVIEW

File: packages/server/chronos.ts [hunk 1]
```diff
@@ -117,27 +117,34 @@ const chronos = () => {
...
+  leader.on('elected', () => {
+    Logger.log(`\n🌾🌾🌾 Server ID: ${SERVER_ID} Elected for Chronos           🌾🌾🌾`)
+    chronos()
+  })
+  leader.on('revoked', () => {
+    Logger.log(`\n🌾🌾🌾 Server ID: ${SERVER_ID} Lost Chronos           🌾🌾🌾`)
+    runningJobs.forEach((job) => job.stop())
+  })
+  leader.start()
+  return () => leader.stop()
```
Comment (Dschoordsch) [inline packages/server/chronos.ts:147]: -1 this does not do `runningJobs.forEach((job) => job.stop())` like we do when it's revoked.

File: packages/server/LeaderElector.ts [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+  redlock: Redlock
+  lockKey: string
+  lockTTL: number
+  lock: Lock | null = null
+  renewTimer: NodeJS.Timeout | undefined = undefined
+  running: boolean = false
+  constructor(redis: RedisInstance, prefix: string, lockTTL: number) {
+    super()
+    this.redis = redis
+    this.redlock = new Redlock([this.redis], {retryCount: -1})
```
Comment (Dschoordsch) [inline packages/server/LeaderElector.ts:23]: -1 I'm not sure I totally understand what we're doing here. If we have a `retryCount: -1` a.k.a [infinity](https://github.com/mike-marcacci/node-redlock/blob/main/src/index.ts#L429-L430), then I would think that `tryAcquireLock()` would never return without a lock unless we run into some redis error.
