### PR TITLE
fix: task highlight sticks when adding a due date

### LINKED ISSUE #7169: Task highlight sticks when adding a due date
## How to reproduce
* join a check-in with Hilde and Olga
* advance to solo update from Hilde with 2 tasks visible
* Hilde changes the due date of task 1 and moves the mouse to task 2

## Expected behaviour
Olga sees task 1 highlighted and then task 2

## Actual behaviour
Olga sees task 1 still highlighted when Hilde moves to task 2, so both tasks are highlighted

EE: 1h to find root cause or create follow up

### PR DESCRIPTION
**Pull request by gitstart**
# Description

Fixes/Partially Fixes #7169

### Please include a summary 

- How to reproduce
- join a check-in with Hilde and Olga
- advance to solo update from Hilde with 2 tasks visible
- Hilde changes the due date of task 1 and moves the mouse to task 2

### Expected behaviour
Olga sees task 1 highlighted and then task 2

Actual behaviour
Olga sees task 1 still highlighted when Hilde moves to task 2, so both tasks are highlighted

### Demo 
[loom](https://www.loom.com/share/366055c8688b4ac69918ae6b0822abe9)

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by gitstart-parabol** [comment]
@BartoszJarocki this PR is ready for review

File: packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx [hunk 1]
```diff
@@ -100,14 +101,15 @@ const OutcomeCardContainer = memo((props: Props) => {
...
-
   useScrollIntoView(ref, !contentState.hasText())
+  useClickAway(ref, () => setIsTaskHovered(false))
   return (
     <Wrapper
       tabIndex={-1}
       className={className}
       onMouseEnter={() => setIsTaskHovered(true)}
       onMouseLeave={() => setIsTaskHovered(false)}
+      onMouseOver={() => setIsTaskHovered(true)}
```
Comment (BartoszJarocki) [inline packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx:112]: +1 what's the reason for adding this? I tested and everything seems to work correctly with just using `useClickAway`

Comment (gitstart-instrumental) [reply packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx:112]: @BartoszJarocki here's the explanation for this

Behavior Before implementation "Onmouseover is not added"
https://www.loom.com/share/8716b3e52f9e43da9d9916ec804f1290

After implementation "Onmouseover is added"
https://www.loom.com/share/42f0c35fb07049ed9c3f624b070a8bd6

Comment (gitstart-parabol) [reply packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx:112]: @BartoszJarocki here's the explanation for this

Behavior Before implementation "Onmouseover is not added"
https://www.loom.com/share/8716b3e52f9e43da9d9916ec804f1290

After implementation "Onmouseover is added"
https://www.loom.com/share/42f0c35fb07049ed9c3f624b070a8bd6

**Comment by gitstart-parabol** [comment]
@BartoszJarocki what's the verdict on this?
