### PR TITLE
Returning refreshed token from fresh atlassian auth loader

### LINKED ISSUE #5690: Atlassian Integration - Error: Unauthorized
Affected 81 users in a couple of days, happened more than 1.5k times
We should double check if our token refresh mechanism works correctly

https://sentry.io/organizations/parabol/issues/2563520365/?referrer=github_plugin

```
Error: Unauthorized
  File "./packages/client/utils/AtlassianManager.ts", line 314, in p.get
    return new Error(json.message)
  ?, in runMicrotasks
  File "./packages/client/utils/AtlassianManager.ts", line 548, in async p.getIssue
    const issueRes = await this.get
```

### PR DESCRIPTION
**Pull request by BartoszJarocki**
Fixes #5690

### CODE REVIEW

File: packages/server/dataloader/atlassianLoaders.ts [hunk 1]
```diff
@@ -63,6 +63,12 @@ export const freshAtlassianAuth = (parent: RootDataLoader) => {
                 refreshToken: updatedRefreshToken
               }))
             await upsertAtlassianAuths(updatedSameJiraAccountAtlassianAuths)
+
+            return {
+              ...atlassianAuthToRefresh,
+              accessToken,
```
Comment (tianrunhe) [inline packages/server/dataloader/atlassianLoaders.ts:69]: nit: rename this to `updatedAccessToken` to make it clear it's the new one, and also matches the naming pattern with `updatedRefreshToken`

**Review by tianrunhe — APPROVED** [review]
