### PR TITLE
fix: emoji tooltip info is wrong in a standup discussion drawer

### LINKED ISSUE #8810: Stand-up response side sheet, emoji tooltip info is wrong
### Repro steps
- Go to a Standup meeting
- Open the response side sheet thread by tapping on Reply
- Hover over the first emoji, see what it says
- Then tap Reply on another card to swap out the side sheet response and thread
- Hover over the first emoji, at some point after swapping responses by tapping reply on response cares in the grid view (main area left of the side sheet), this emoji in the side sheet will have what seems like tooltip info from the emoji of the previous response that was in the side sheet view

E.g. here the 2 hearts on 1 response in side sheet is showing the tooltip for 3 sparkles that was left on another response (as seen in the response grid card)

Screen Shot 2023-09-08 at 14 52 25
Screen Shot 2023-09-08 at 14 52 46

### Effort
- 1 hour to triage query update on side sheet view and emoji or similar. Update here

### PR DESCRIPTION
**Pull request by BartoszJarocki**
# Description

Fixes #8810

## Demo

No demo

## Testing scenarios

- [ ] Join standup with at least two users, add responsed and reactions; open discussion drawers and make sure emoji tooltips are correct

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

File: packages/client/components/TeamPrompt/TeamPromptDrawer.tsx [hunk 1]
```diff
@@ -89,7 +107,15 @@ const TeamPromptDrawer = ({meetingRef, isDesktop}: Props) => {
       sidebarWidth={DiscussionThreadEnum.WIDTH}
     >
       <Drawer isDesktop={isDesktop} isMobile={isMobile} isOpen={isRightDrawerOpen}>
-        {renderedInnerDrawer}
+        {shouldRenderDiscussionDrawer() ? (
+          <TeamPromptDiscussionDrawer
+            key={meeting.localStageId!}
```
Comment (BartoszJarocki) [inline packages/client/components/TeamPrompt/TeamPromptDrawer.tsx:112]: this make sure we have a different instance of a drawer for each user

File: packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx [hunk 2]
```diff
@@ -181,7 +181,7 @@ const TeamPromptDiscussionDrawer = ({meetingRef, onToggleDrawer}: Props) => {
           header={
             <DiscussionHeaderWrapper>
               <PromptResponseEditor content={contentJSON} readOnly={true} />
-              <StyledReactjis reactjis={reactjis} onToggle={onToggleReactji} />
+              <StyledReactjis key={localStageId} reactjis={reactjis} onToggle={onToggleReactji} />
```
Comment (BartoszJarocki) [inline packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx:184]: this is the actual fix. we use `reactji` id as a key, which is the same for all the discussions. adding key here, makes sure reactji section is user specific

File: packages/client/components/TeamPrompt/TeamPromptDrawer.tsx [hunk 3]
```diff
@@ -73,13 +86,18 @@ const TeamPromptDrawer = ({meetingRef, isDesktop}: Props) => {
     })
   }
 
-  // Render the discussion thread if it can be rendered, otherwise fall back on the work sidebar.
-  // :TRICKY: Elements rendered with JSX never return null, so we need to render both possible
-  // internal drawers via function calls in order to nullish coalesce. We also have to call both
-  // every time for the React hooks to be consistent.
-  const renderedDiscussionDrawer = TeamPromptDiscussionDrawer({meetingRef: meeting, onToggleDrawer})
-  const renderedWorkDrawer = TeamPromptWorkDrawerRoot({meetingRef: meeting, onToggleDrawer})
-  const renderedInnerDrawer = renderedDiscussionDrawer ?? renderedWorkDrawer
```
Comment (BartoszJarocki) [inline packages/client/components/TeamPrompt/TeamPromptDrawer.tsx:82]: i'd rather fetch more data than use a hacky way of rendering components. this isn't guaranteed to work in a future versions of react and may have unintended consequences

**Review by jmtaber129 — APPROVED** [review]
