### PR TITLE
fix: Remove duplicate org users

### LINKED ISSUE #9302: Bug: duplicate OrganizationUser objects are created in some cases
A newly added test to check that we're not creating duplicated `OrganizationUser` objects is failing randomly. It appears there are still duplicates created in certain cases.

> @Dschoordsch it looks like this produced a flaky test result for me-- failed first test, passed on second try. 
>
> https://github.com/ParabolInc/parabol/actions/runs/7278378730/job/19832437203. Should I make an issue for this?
>
>edit: happened again, so likely not a fluke: https://github.com/ParabolInc/parabol/actions/runs/7278798261/attempts/1?pr=9295

_Originally posted by @mattkrick in https://github.com/ParabolInc/parabol/issues/9290#issuecomment-1864849230_

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Fixes #9302
Add a constraint that forbids duplicate organization users. There is no need to have multiple entries as the join/leave events are already captured in OrganizationUserAudit.

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

- [ ] Remove a user Joe from an organization
- [ ] Add Joe again
- [ ] check that Joe can see the org correctly

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label https://github.com/ParabolInc/parabol/labels/Skip%20Maintainer%20Review if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

File: packages/server/billing/helpers/adjustUserCount.ts [hunk 1]
```diff
@@ -83,7 +77,16 @@ const addUser = async (orgIds: string[], user: IUser, dataLoader: DataLoaderWork
...
+    .onConflict((oc) =>
+      oc.constraint('unique_org_user').doUpdateSet({
+        joinedAt: sql`CURRENT_TIMESTAMP`,
+        removedAt: null,
+        inactive: false,
+        role: null,
+        suggestedTier: null,
+        tier: (eb) => eb.ref('excluded.tier')
+      })
+    )
```
Comment (Dschoordsch) [inline packages/server/billing/helpers/adjustUserCount.ts:89]: I'm mostly concerned with this part. Previously we just created a new org user when a new user joined, but now we have to reset all the old fields that should be reset.

File: packages/server/postgres/migrations/1725438336254_addOrganizationUserUniqueConstraint.ts [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+           )
+        )
+        -- or newer non-removed
+        OR (k."removedAt" IS NULL AND d."removedAt" IS NULL AND k.id > d.id)
+      );
+  `.execute(pg)
+
+  await pg.schema
+    .alterTable('OrganizationUser')
+    .addUniqueConstraint('unique_org_user', ['orgId', 'userId'])
```
Comment (mattkrick) [inline packages/server/postgres/migrations/1725438336254_addOrganizationUserUniqueConstraint.ts:34]: back in the days of proration, we needed to keep track of `removedAt` since some users would join an org, then leave it, then join again & we didn't want to treat them as a new user with a grace period.

I see the unique constraint doesn't include `removedAt`, which means only 1 row per user per org, so if a user joins, then leaves, then joins again, what happens?
The logic here would say `removedAt` doesn't get reset: https://github.com/ParabolInc/parabol/blob/63bf930989f1493f54d36407a990863519b80528/packages/server/billing/helpers/adjustUserCount.ts#L86. At least I think, I didn't actually test this yet

File: packages/server/billing/helpers/adjustUserCount.ts (hunk 1 above)
Comment (mattkrick) [reply packages/server/billing/helpers/adjustUserCount.ts:89]: LGTM! i don't think we use trialStartDate anymore so we can ignore that column.

**Review by mattkrick — APPROVED** [review]
