### PR TITLE
fix(teams-limit): fix locked message in usage stats

### LINKED ISSUE #7838: Teams limit: show different message in usage stats when org is locked
When an org is locked, we still show a countdown message on the usage stats page:

image

Show different message, something like: "Please upgrade to continue using Parabol"

### PR DESCRIPTION
**Pull request by igorlesnenko**
Fixes #7838

When the time is up, instead of the countdown timer show another message

image

**How to test:**

- Set scheduledLockAt on the org = new Date()
- See the message from the screenshot above

### CODE REVIEW

**Review by acressall — APPROVED** [review]

File: packages/client/components/InsightsDomainNudge.tsx [hunk 1]
```diff
@@ -132,12 +139,13 @@ const InsightsDomainNudge = (props: Props) => {
...
               <BoldText>{`${Threshold.MAX_STARTER_TIER_TEAMS} free teams`}</BoldText>
-              {toBeLockedOrg?.scheduledLockAt && (
+              {scheduledLockAt && !isLocked && (
                 <>
                   {`. Your free access will end in `}
-                  <BoldText>{`${relativeDate(toBeLockedOrg?.scheduledLockAt)}.`}</BoldText>
+                  <BoldText>{`${relativeDate(scheduledLockAt)}.`}</BoldText>
                 </>
               )}
+              {isLocked && `. Please upgrade to continue using Parabol`}
```
Comment (nickoferrall) [inline packages/client/components/InsightsDomainNudge.tsx:148]: +1 could add a full stop at the end of this sentence: `Please upgrade to continue using Parabol.`

**Review by nickoferrall — APPROVED** [review]
LGTM!
