### PR TITLE
fix: limit the Azure DevOps work items fetched

### LINKED ISSUE #10906: Azure DevOps: initial fetch of issues times out
A customer [reported](https://parabol.slack.com/archives/C4JAUUZ9P/p1739991707559949?thread_ts=1739212693.591459&cid=C4JAUUZ9P) 🔒 they get an error when trying to load ADO issues in a Sprint Poker.
The [log](https://app.datadoghq.com/logs?query=host%3Agke-saas-production-gke-default-ed496129-8rea.c.parabol-saas-production.internal%20service%3Aparabol%20container_id%3Ac8b99d0e72b0ea9f0d71bfeda09a7baf0f1c3e4b7bc7da852b715ee80f0ef017%20filename%3A0.log&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZUfjIeeAACvNC5kvclqtgAA&event=AwAAAZUfjH7Os_22gAAAABhBWlVmakllZUFBQ3ZOQzVrdmNscXRnQUEAAAAkMDE5NTFmY2ItYjlmZi00M2IzLWIxM2UtZmFhN2NlODU0ZmVhAABnfA&fromUser=true&graphType=flamegraph&messageDisplay=inline&refresh_mode=paused&sort=time&spanID=865412263130602416&storage=hot&stream_sort=time%2Cdesc&to_event=AwAAAZUfjH7Os_22gAAAABhBWlVmakllZUFBQ3ZOQzVrdmNscXRnQUEAAAAkMDE5NTFmOTMtYjE5MS00YWZmLWE4ODktMjlkOGQ4MWJjYThkAAADPw&viz=&from_ts=1739990756078&to_ts=1739991056079&live=false) 🔒 shows that the time is spent in `query AzureDevOpsScopingSearchResultsQuery` in the field `workItems: AzureDevOpsWorkItemConnection!` with 17.6s of 17.7s total.

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Fixes #10906 
Limit the number of work items fetched in ADO scoping phase.

Pagination is still not implemented, but seems to be absent for other integrations in scoping.

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Step 1
  - Step 2...

- [ ] Scenario B
  - Step 1
  - Step 2....

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label https://github.com/ParabolInc/parabol/labels/Skip%20Maintainer%20Review if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

File: packages/server/dataloader/azureDevOpsLoaders.ts [hunk 1]
```diff
@@ -665,55 +646,3 @@ const getMappedAzureDevOpsWorkItem = async (
   }
   return azureDevOpsWorkItem
 }
-
-export const azureDevOpsWorkItems = (
```
Comment (Dschoordsch) [inline packages/server/dataloader/azureDevOpsLoaders.ts:669]: Wasn't used

File: packages/server/graphql/public/types/AzureDevOpsIntegration.ts [hunk 2]
```diff
@@ -24,29 +17,45 @@ const AzureDevOpsIntegration: AzureDevOpsIntegrationResolvers = {
...
+          allUserWorkItems.map((userWorkItem) => {
+            return {
+              ...userWorkItem,
+              updatedAt: new Date()
+            }
+          })
+        )
+        return connectionFromTasks(workItems, first, undefined)
+      }
+    } catch (error) {
```
Comment (Dschoordsch) [inline packages/server/graphql/public/types/AzureDevOpsIntegration.ts:53]: Returning an error from a dataloader batch function makes the dataloader throw.
