### PR TITLE
fix: dynamic text for instruction text

### LINKED ISSUE #10072: Fix retro tooltips
The tooltips don't take into account some settings and show wrong text:
* retro reflection phase always says it's anonymous
* retro voting phase does not take current vote settings into account

### PR DESCRIPTION
**Pull request by iamhks**
# Description

Fixes #10072 
Made code changes to support dynamic text for votes help tool tip & reflections help tool tip
Adding screenshots:
- When Anonymous is checked:
Screenshot 2025-03-05 at 03 09 58

- When Anonymous is un-checked:
Screenshot 2025-03-05 at 03 10 33

- Vote Settings(opening in 2 tabs to show both settings and instruction text):
Screenshot 2025-03-05 at 03 12 50

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label https://github.com/ParabolInc/parabol/labels/Skip%20Maintainer%20Review if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by Dschoordsch** [comment]
@iamhks You missed some part of the issue: "retro reflection phase always says it's anonymous"

**Comment by iamhks** [comment]
Oh yes! I'll keep the text anonymous if that setting is enabled and remove the line if the setting is disabled.
Does that work @Dschoordsch or do you have any alternate suggestion?

**Comment by Dschoordsch** [comment]
That would be good.

**Comment by iamhks** [comment]
Hi @Dschoordsch, please have a look. Updated the screenshots as well.

**Comment by iamhks** [comment]
FYI: I'll be out of station for about a week and a half, will be able to resolve any comments after I am back.

**Comment by Dschoordsch** [comment]
Sorry, missed this. Looks good so far, will test tomorrow.

**Comment by iamhks** [comment]
👍

File: packages/client/components/MeetingHelp/ReflectHelpMenu.tsx [hunk 1]
```diff
@@ -19,10 +35,12 @@ const ReflectHelpMenu = forwardRef((_props: Props, ref: any) => {
...
         As a group, reflect on how work’s going for a specific project or timeframe.
       </HelpMenuCopy>
-      <HelpMenuCopy>
-        During this phase nobody can see your reflections. After this phase reflections will be
-        visible, but remain anonymous.
-      </HelpMenuCopy>
+      {!disableAnonymity && (
+        <HelpMenuCopy>
+          During this phase nobody can see your reflections. After this phase reflections will be
+          visible, but remain anonymous.
```
Comment (Dschoordsch) [inline packages/client/components/MeetingHelp/ReflectHelpMenu.tsx:41]: -1 I think we should keep the paragraph and only put "but remain anonymous" behind the `disableAnonymity` check.

**Review by Dschoordsch — CHANGES_REQUESTED** [review]
Only a small nit

File: packages/client/components/MeetingHelp/ReflectHelpMenu.tsx (hunk 1 above)
Comment (iamhks) [reply packages/client/components/MeetingHelp/ReflectHelpMenu.tsx]: Updated the code.

**Review by Dschoordsch — APPROVED** [review]
