### PR TITLE
fix: Allow login with google with ad blocker enabled

### LINKED ISSUE #8725: Users with certain Chrome extensions can't log in or create an account

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Fixes #8725 

The ad blocker (like uBlock origin) are blocking a call to `gtag` which never resolves and thus leaves the app hanging with the popup window blank. Added a timeout for the call.

## Demo

https://www.loom.com/share/3f301ab7d4f34525af3201161184e393?sid=ca8e275e-2177-4c5c-a882-2f7f98135784

## Testing scenarios

- [ ] with uBlock origin installed and activated try login with google

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

**Review by igorlesnenko — APPROVED** [review]
It works!

File: packages/client/utils/getAnonymousId.ts [hunk 1]
```diff
@@ -6,6 +6,8 @@ const retrieveGtagClientId = async (
 ): Promise<string | undefined> => {
   return new Promise((resolve) => {
     gtag('get', measurementId, 'client_id', resolve)
+    // if the call gets blocked, then it might never resolve
+    window.setTimeout(() => resolve(undefined), 1000)
```
Comment (Dschoordsch) [inline packages/client/utils/getAnonymousId.ts:10]: @tianrunhe just tagging you so you can see there is a timeout now.

Comment (tianrunhe) [reply packages/client/utils/getAnonymousId.ts:10]: Yeah I've taken a look at your PR yesterday. Thanks for fixing this!
