### PR TITLE
fixed ~200 noImplicitAny errors, mostly on graphql type files

### LINKED ISSUE #5314: Add noImplicitAny to server tsconfig (Part 1 of 8)
When we migrated to typescript from javascript, it was too expensive to turn on `noImplicitAny` because it was hard enough just making the switch.

Today, having `noImplicitAny` could catch a lot of errors that I'm seeing in code reviews.
The problem is that there are 1600 errors!
This is too many for any one person to do in a sprint.
However, the benefit of having this turned on for new code is pretty great.

So, I propose we share the love & chip away at it:
- [ ] turn on `noImplicitAny` in the server tsconfig file
- [ ] fix ~200 errors
- [ ] turn it off again in the tsconfig file & submit the PR
- [ ] we'll merge it blindly
- [ ] create a copy of this issue named Part (2 of 8) so we can re-prioritize for the next person. We'll keep doing this until it's done

AC
- [ ] 200+ `noImplicitAny` errors are fixed in the server package

Estimate: 4 hours

### PR DESCRIPTION
**Pull request by tiffanyhan**
Resolves #5314

### CODE REVIEW

File: packages/server/graphql/types/Organization.ts [hunk 1]
```diff
@@ -20,7 +22,7 @@ import Team from './Team'
 import TierEnum from './TierEnum'
 import User from './User'
 
-const Organization = new GraphQLObjectType<any, GQLContext>({
+const Organization: GraphQLObjectType<any, GQLContext> = new GraphQLObjectType<any, GQLContext>({
```
Comment (mattkrick) [inline packages/server/graphql/types/Organization.ts:25]: interesting that TS has to infer `any` because of the circular reference in the fields!

**Comment by mattkrick** [comment]
LGTM! not sure if still in draft or ready to merge, but feel free to merge when ready
