### PR TITLE
fix: Show error message when creating Jira task fails

### LINKED ISSUE #6320: Unable to create a new Jira issue in Poker
When creating a new Jira issue in Poker in prod, I can enter the title but the new issue doesn't submit when pressing enter or clicking outside of the input. I can see in the network requests that the mutation hasn't been executed. 

It does work in GitHub and Parabol.

create-jira-issue

### AC

- [ ] Can create a new Jira issue in Poker

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Fixes #6320 
When creating a Jira task in Sprint Poker failed, the error message wasn't send properly to the client. It also wouldn't be shown to the client.
If task creation failed, show the error message now for 5s.

This does not fix the underlying issue, but presents it to the user, so they hopefully can react accordingly or report more detailed errors.

## Demo

https://www.loom.com/share/d798bb9765394f2a9097a51a1fea41e4?sid=6da48e5b-40ec-4599-88cc-36f3b51e4b8e

## Testing scenarios

- [ ] Try to create a **Jira** issue which produces an error
- [ ] see the error message
- [ ] repeat for **GitHub**
- [ ] repeat for **GitLab**
- [ ] repeat for **Azure DevOps**

Run `node scripts/toolbox/postDeploy.js` if you're missing some of the integrations.
You can test error scenarios by adding a something like
```ts
return {error: new Error('Georg was here')}
```
in https://github.com/ParabolInc/parabol/blob/063a526dbcfd6340f4daa645c5875c679745519b/packages/server/graphql/mutations/helpers/createTaskInService.ts#L59

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

File: packages/server/graphql/public/types/CreateTaskPayload.ts [hunk 1]
```diff
@@ -4,13 +4,20 @@ import errorFilter from '../../errorFilter'
...
+  error?: Error
+  taskId?: string
   notificationIds?: string[]
 }
 
 const CreateTaskPayload: CreateTaskPayloadResolvers = {
+  error: async ({error}) => {
+    if (!error) return null
+    return {
+      message: error.message
```
Comment (Dschoordsch) [inline packages/server/graphql/public/types/CreateTaskPayload.ts:16]: Although the error already has the correct shape, without this resolver the error member in source would not be used as source here, but treated as if it was thrown by graphql.

**Comment by Dschoordsch** [comment]
I tried to add [`status=live`](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-projects/#api-rest-api-3-project-search-get) filter to the projects listing to filter out the non-existent projects, but that does not do anything.

**Review by igorlesnenko — APPROVED** [review]
