### PR TITLE
Sort the reflection goups on server side after REFLECT phase

### LINKED ISSUE #4495: Sort reflections between Reflect and Group phase
between the reflect & group phase, we can do some analysis on the content of the reflections & take a best guess at which ones belong with other ones.

- We know magically grouping them doesn't work. people don't like it.
- team retro suggests groups & makes people accept/deny the magical groups. this is better.
- my suggestion is to simply put similar cards next to each other. that way, folks feel like they did it, it was their idea. It'll be one of those subtle things why parabol just makes meetings better, but you don't know why.

AC
- [x] When the facilitator navigates to the grouping phase for the very first time, the navigateMeeting mutation calls handleCompletedStage
- [x] in handleCopletedStage, when the stage completed is the reflect stage, we update the `sortOrder` for all reflection groups after removing the empty reflections (L19)
- [x]  The ReflectPhaseCompletePayload includes a `reflectionGroups` field
- [x] On the client, the navigatemeetingMutation reqeusts `reflectionGroups { sortOrder}` from the reflect phase complete payload
- [x] when a reflection is ungrouped, the sort order of its old group is identified & the ungrouped reflection is put into its own group. The sort order of that new group is determined based off the `(old group's sortOrder + the sort order of the group after it) / 2 + noise()` unless the old group is at the bottom. if that's the case, then it is `old group's sortOrder + 1 + noise()`
- [x] when a new reflection is created, it's put at the bottom of the shortest sub column. To accomplish this, the reflection group's sortOrder is calculated by finding the subColumnIdx with the fewest number of reflections & then grabbing the sort order of the bottom reflection group & adding 1 + noise() to that.

Estimate: 8 hours

### PR DESCRIPTION
**Pull request by tianrunhe**
Resolves #4495

Tests:

- [ ] When user navigates from reflect phase to group phase, the reflection cards are sorted within each column
- [ ] If user creates reflection groups, the column won't sort again
- [ ] When user ungroups, the left-alone card stays close with the old group
- [ ] Expanding sub-columns won't break any of the above-mentioned behaviors

### CODE REVIEW

File: packages/client/mutations/NavigateMeetingMutation.ts [hunk 1]
```diff
@@ -142,6 +146,11 @@ export const navigateMeetingTeamUpdater: SharedUpdater<NavigateMeetingMutation_t
       reflectPrompt?.setValue([], 'editorIds')
     })
   }
+
+  const reflectionGroups = meeting.getLinkedRecords('reflectionGroups')
+  const sortedReflectionGroups = reflectionGroups.sort((a, b) =>
```
Comment (mattkrick) [inline packages/client/mutations/NavigateMeetingMutation.ts:151]: `reflectionGroups.slice().sort`, sort mutates the current array instead of doing a shallow clone.
relay requires a new object when you call `setLinkedRecords` because internally it does shallow object equality comparisons

File: packages/client/mutations/NavigateMeetingMutation.ts [hunk 2]
```diff
@@ -183,6 +192,38 @@ const NavigateMeetingMutation = (
               setLocalStageAndPhase(store, meetingId, completedStageId)
             }
           }
+          if (phaseType === REFLECT) {
```
Comment (mattkrick) [inline packages/client/mutations/NavigateMeetingMutation.ts:195]: whoaaaa, double duty!
why not just wait for the sort order to come back from the server?

File: packages/server/graphql/mutations/helpers/handleCompletedStage.ts [hunk 3]
```diff
@@ -16,7 +24,47 @@ const handleCompletedRetrospectiveStage = async (
   dataLoader: DataLoaderWorker
 ) => {
   if (stage.phaseType === REFLECT || stage.phaseType === GROUP) {
-    const data = await removeEmptyReflections(meeting)
+    const data: Record<string, any> = await removeEmptyReflections(meeting)
+
+    if (stage.phaseType === REFLECT) {
+      const r = await getRethink()
+      const now = new Date()
+      const reflectionGroups = await dataLoader
```
Comment (mattkrick) [inline packages/server/graphql/mutations/helpers/handleCompletedStage.ts:32]: nit: can combine these 2 in a `Promise.all` so we can return faster

File: packages/server/graphql/mutations/helpers/handleCompletedStage.ts [hunk 4]
```diff
@@ -16,7 +24,47 @@ const handleCompletedRetrospectiveStage = async (
...
+        .table('RetroReflection')
+        .getAll(meeting.id, {index: 'meetingId'})
+        .filter({isActive: true})
+        .orderBy('createdAt')
+        .run()
+      const {reflectionGroupMapping, autoGroupThreshold, nextThresh} = groupReflections(
+        reflections,
+        AUTO_GROUPING_THRESHOLD
+      )
+      console.log(`autoGroupThreshold = ${autoGroupThreshold}; nextThresh = ${nextThresh}`)
```
Comment (mattkrick) [inline packages/server/graphql/mutations/helpers/handleCompletedStage.ts:45]: remove log

File: packages/server/graphql/mutations/helpers/handleCompletedStage.ts [hunk 5]
```diff
@@ -16,7 +24,47 @@ const handleCompletedRetrospectiveStage = async (
...
+
+      reflectionGroups.sort((groupA, groupB) => {
```
Comment (mattkrick) [inline packages/server/graphql/mutations/helpers/handleCompletedStage.ts:47]: slice first! here you're mutating an array provided by a dataloader. that means ANY other function that is using that same dataloader is going to get mutated & depending on when this runs, that means it'll be nondeterministic

File: packages/server/graphql/mutations/helpers/handleCompletedStage.ts [hunk 6]
```diff
@@ -16,7 +24,47 @@ const handleCompletedRetrospectiveStage = async (
...
+        const newGroupIdA = reflectionGroupMapping[groupA.id]
+        const newGroupIdB = reflectionGroupMapping[groupB.id]
+        return newGroupIdA.localeCompare(newGroupIdB)
```
Comment (mattkrick) [inline packages/server/graphql/mutations/helpers/handleCompletedStage.ts:50]: why `localeCompare` instead of just a < b ? -1 : 1?

File: packages/server/graphql/mutations/helpers/handleCompletedStage.ts [hunk 7]
```diff
@@ -16,7 +24,47 @@ const handleCompletedRetrospectiveStage = async (
...
+      })
+
+      reflectionGroups.forEach(async (group, index) => {
+        group.sortOrder = index
+        await r
```
Comment (mattkrick) [inline packages/server/graphql/mutations/helpers/handleCompletedStage.ts:55]: don't use async/await in a `forEach`, it doesn't act how you think it acts!

instead, try `await Promise.all(reflectionGroups.map(() => return r.table(...))`

File: packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts [hunk 8]
```diff
@@ -12,10 +12,22 @@ const removeReflectionFromGroup = async (reflectionId, {dataLoader}) => {
...
   if (!reflection) throw new Error('Reflection not found')
   const {reflectionGroupId: oldReflectionGroupId, meetingId, promptId} = reflection
+  const oldReflectionGroup = await r
+    .table('RetroReflectionGroup')
+    .get(oldReflectionGroupId)
+    .run()
+  const {sortOrder: oldSortOrder} = oldReflectionGroup
+  const maxSortOrder = await r
+    .table('RetroReflectionGroup')
+    .getAll("1kHnE9uN5C", {index: 'meetingId'})('sortOrder')
```
Comment (mattkrick) [inline packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts:22]: this ain't good

File: packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts [hunk 9]
```diff
@@ -12,10 +12,22 @@ const removeReflectionFromGroup = async (reflectionId, {dataLoader}) => {
...
+    .max()
+    .default(0)
+    .run()
   const meeting = await dataLoader.get('newMeetings').load(meetingId)
 
   // RESOLUTION
-  const reflectionGroup = new ReflectionGroup({meetingId, promptId})
+  const newSortOrder = oldSortOrder === maxSortOrder ? oldSortOrder + 1 : (oldSortOrder + (oldSortOrder + 1)) / 2
```
Comment (mattkrick) [inline packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts:29]: that last piece is just `oldSortOrder + .5`. that doesn't work because what if the next 5 reflection groups all have sort orders less than .5 greater?
you need to grab the sort order of the next item

**Review by mattkrick — CHANGES_REQUESTED** [review]

File: packages/client/mutations/NavigateMeetingMutation.ts (hunk 2 above)
Comment (tianrunhe) [reply packages/client/mutations/NavigateMeetingMutation.ts:195]: I saw flickering without this part in optimistic updater

Comment (mattkrick) [reply packages/client/mutations/NavigateMeetingMutation.ts:195]: hmmm, lemme see if i can find a way around that.
my concern is that we're requiring a whole lot more code (the clustering algo, etc), all the reflection entities, and performing a whole lot of extra work & it only benefits the facilitator for a split second.

Comment (mattkrick) [reply packages/client/mutations/NavigateMeetingMutation.ts:195]: @tianrunhe check out L190 above. for the vote phase, we undo changing the facilitatorStageId. that avoids the flicker!

File: packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts [hunk 10]
```diff
@@ -12,10 +12,30 @@ const removeReflectionFromGroup = async (reflectionId, {dataLoader}) => {
     .run()
   if (!reflection) throw new Error('Reflection not found')
   const {reflectionGroupId: oldReflectionGroupId, meetingId, promptId} = reflection
+  const oldReflectionGroup = await r
```
Comment (mattkrick) [inline packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts:15]: is it safe to use a dataloader to get?
can we combine the next 3 async calls?

File: packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts [hunk 11]
```diff
@@ -12,10 +12,30 @@ const removeReflectionFromGroup = async (reflectionId, {dataLoader}) => {
...
+    .table('RetroReflectionGroup')
+    .getAll(meetingId, {index: 'meetingId'})
+    .filter({isActive: true})
+    .orderBy('sortOrder')
+    .run()
   const meeting = await dataLoader.get('newMeetings').load(meetingId)
 
   // RESOLUTION
-  const reflectionGroup = new ReflectionGroup({meetingId, promptId})
+  const nextReflectionGroupIndex =
```
Comment (mattkrick) [inline packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts:29]: if the client lags, the oldReflectionGroup may already be inactive, which would result in `-1 + 1`, which would put this at the top (if the column has at least 1 card in it) instead of the bottom

File: packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts [hunk 12]
```diff
@@ -12,10 +12,30 @@ const removeReflectionFromGroup = async (reflectionId, {dataLoader}) => {
...
+    reflectionGroups.findIndex(({id}) => id === oldReflectionGroup.id) + 1
+  let newSortOrder
+  if (nextReflectionGroupIndex >= reflectionGroups.length) {
+    newSortOrder = oldSortOrder + 1
+  } else {
+    const nextSortOrder = reflectionGroups[nextReflectionGroupIndex].sortOrder
```
Comment (mattkrick) [inline packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts:35]: reflectionGroups[nextReflectionGroupIndex] is not guaranteed. what if no cards are in the column?

File: packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts [hunk 13]
```diff
@@ -12,10 +12,30 @@ const removeReflectionFromGroup = async (reflectionId, {dataLoader}) => {
...
+    .run()
   const meeting = await dataLoader.get('newMeetings').load(meetingId)
 
   // RESOLUTION
-  const reflectionGroup = new ReflectionGroup({meetingId, promptId})
+  const nextReflectionGroupIndex =
+    reflectionGroups.findIndex(({id}) => id === oldReflectionGroup.id) + 1
+  let newSortOrder
+  if (nextReflectionGroupIndex >= reflectionGroups.length) {
+    newSortOrder = oldSortOrder + 1
```
Comment (mattkrick) [inline packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts:33]: needs noise. it's possible this function gets called by 2 different folks at the (almost) exact moment.

File: packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts [hunk 14]
```diff
@@ -12,10 +12,30 @@ const removeReflectionFromGroup = async (reflectionId, {dataLoader}) => {
...
+  } else {
+    const nextSortOrder = reflectionGroups[nextReflectionGroupIndex].sortOrder
+    newSortOrder = (oldSortOrder + nextSortOrder) / 2
```
Comment (mattkrick) [inline packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts:36]: needs noise, 2 people could call this at the same time

File: packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts [hunk 15]
```diff
@@ -12,10 +12,30 @@ const removeReflectionFromGroup = async (reflectionId, {dataLoader}) => {
...
+  }
+  const reflectionGroup = new ReflectionGroup({meetingId, promptId, sortOrder: newSortOrder})
   await r
```
Comment (mattkrick) [inline packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts:39]: could we combine a few of these await clauses? less awaiting means less of a chance of race conditions

File: packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts (hunk 11 above)
Comment (tianrunhe) [reply packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts:29]: I don't quite follow on this one. Can you elaborate more? Appreciate it!

File: packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts (hunk 12 above)
Comment (tianrunhe) [reply packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts:35]: If there are no cards, `reflectionGroups.length === 0` and `nextReflectionGroupIndex === 1` so it will execute the if block, right?

File: packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts (hunk 11 above)
Comment (mattkrick) [reply packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts:29]: `findIndex` returns -1 if no match is found.
that's possible because `oldReflectionGroupId` could refer to a reflection group that has already gone away

File: packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts (hunk 12 above)
Comment (mattkrick) [reply packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts:35]: yep, you're right!

Comment (mattkrick) [reply packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts:35]: for things like this, it's often nicer to do conditional access, that way in a couple weeks when we forget the business logic, we can quickly rule out an undefined error.
e.g. `reflectionGroups[next]?.sortOrder ?? 0`. when i read that single line, i don't have to re-read L29-32 & i know typescript will protect me for the rest of it.

**Comment by mattkrick** [comment]
### Business logic:

- When I ungroup a card from a group in column X, if that card belongs in column X, it should go directly beneath its old group in column X
- When I ungroup a card from a group in column X, if that card belongs in column Y, it should go to the bottom of column Y

```ts
const {promptId} = reflection
const cardsInColumn = await r.table('RetroReflectionGroup').getAll(meetingId, {index: 'meetingId'}).filter({isActive: true, promptId})
let sortOrder = 1e6
if (reflection.promptId === oldReflectionGroup.promptId) {
  // case 1
  const oldGroupIdx = cardsInColumn.findIndex(group => group.id === oldReflectionGroup.id)
  if (oldGroupIdx === -1) {
    // should never happen, but we play it safe
    cardsInColumn[cardsInColumn.length - 1]?.sortOrder + 1 + dndNoise() ?? 1e6
  } else if (oldGroupIdx === cardsInColumn.length - 1) {
    // it's at the bottom!
    sortOrder = cardsInColumn[cardsInColumn.length - 1].sortOrder + 1 + dndNoise()
  } else {
    // stick it directly after the old group
    const oldSortOrder = cardsInColumn[oldGroupIdx].sortOrder
    const afterSortOrder = cardsInColumnn[oldGroupIdx + 1].sortOrder
    sortOrder = (oldSortOrder + afterSortOrder) / 2 + dndNoise()
  }
} else {
   // case 2
   sortOrder = cardsInColumn[cardsInColumn.length - 1]?.sortOrder + 1 + dndNoise() ?? 1e6
}  
```
