### PR TITLE
fix: fix usage stats charts on small amount of data

### LINKED ISSUE #7817: Usage stats meetings chart shows no data if all the meetings happened within one month
Usage stats meetings chart shows no data if all the meetings happened within one month.

**How to reproduce:**

- Create a fresh org
- Run and complete some meetings
- Enable usage stats
- See chars are broken

image

Other charts are not working well too:

image

For the context: #7732

### PR DESCRIPTION
**Pull request by igorlesnenko**
Fixes #7817

Now:

Screenshot 2023-03-07 at 17 28 47

Before:

image

Also fixed axis labels for members and teams charts

image

How to test:

- Create a fresh org
- Run and complete some meetings
- Enable usage stats
- See chars are working fine

### CODE REVIEW

File: packages/client/components/InsightsCharts.tsx [hunk 1]
```diff
@@ -194,6 +200,9 @@ const makeOptions = (title: string, subtitle: string) => {
         grid: {
           display: false,
           drawBorder: false
+        },
+        ticks: {
+          precision: 0
```
Comment (nickoferrall) [inline packages/client/components/InsightsCharts.tsx:205]: +2 nice, I see this removes the floats on the y-axis when there are only two meetings, for example. So the y-axis just has 1 & 2, rather than 1.10, 1.20, 1.30...

**Review by nickoferrall — APPROVED** [review]
LGTM!

File: packages/client/components/InsightsCharts.tsx (hunk 1 above)
Comment (igorlesnenko) [reply packages/client/components/InsightsCharts.tsx:205]: Yes, you can't have 1 and a half meeting :)

**Review by Dschoordsch — APPROVED** [review]
Looks good!
