### PR TITLE
Track fatal bugs per 1,000 sessions

### LINKED ISSUE #5995: Track fatal bugs per 1,000 sessions
By keeping track of the number of fatal bugs per 1,000 sessions, we can better understand whether our app is becoming more or less buggy over time.

### AC

- [ ] Send an event to Segment when a fatal bug happens

### PR DESCRIPTION
**Pull request by nickoferrall**
Fix #5995 

Once we have an idea of the expected number of fatal bugs per 1,000 sessions, we could send a notification to Slack when there's a sudden sharp increase.

I created a chart in amplitude to track this: https://analytics.amplitude.com/parabol/chart/8m2qx3s

### To test

- add the segment env vars
- add a fatal bug, e.g. add an undefined variable to the `TimelineEventCard` component, and then visit the Timeline page at `/me`
- search for your `userId` in amplitude and see that the `Fatal Error` event has been tracked

### CODE REVIEW

File: packages/client/components/ErrorBoundary.tsx [hunk 1]
```diff
@@ -15,20 +17,31 @@ interface State {
...
 class ErrorBoundary extends Component<Props, State> {
   state: State = {
     error: undefined,
     errorInfo: undefined,
-    eventId: undefined
+    eventId: undefined,
+    isOldBrowserErr: false
+  }
+
+  componentDidUpdate() {
```
Comment (nickoferrall) [inline packages/client/components/ErrorBoundary.tsx:31]: I didn't refactor this component to hooks because there isn't a hooks equivalent to `componentDidCatch`: https://reactjs.org/docs/hooks-faq.html#do-hooks-cover-all-use-cases-for-classes

**Comment by nickoferrall** [comment]
Hey @tianrunhe, could you review this one, please?

File: packages/client/components/ErrorBoundary.tsx [hunk 2]
```diff
@@ -15,20 +17,31 @@ interface State {
...
+    const {error, isOldBrowserErr} = this.state
+    if (!error || isOldBrowserErr) return
+    const {atmosphere} = this.props
+    const {viewerId} = atmosphere
+    SendClientSegmentEventMutation(atmosphere, 'Fatal Error', {viewerId})
```
Comment (tianrunhe) [inline packages/client/components/ErrorBoundary.tsx:36]: I don't get why you couldn't do this in `componentDidCatch`?

Comment (nickoferrall) [reply packages/client/components/ErrorBoundary.tsx:36]: `componentDidCatch` re-renders four times and would send four events to Segment

**Comment by tianrunhe** [comment]
@nickoferrall  What's the best/easiest way to test this locally?

**Comment by nickoferrall** [comment]
@tianrunhe I've added testing steps to the PR description 👍

**Comment by tianrunhe** [comment]
Hmm... I couldn't see the events published to Amplitude: https://www.loom.com/share/21b5ee7d9ea14517b312a386b3be378a

**Comment by nickoferrall** [comment]
Thanks for the Loom! It looks like you have the `SEGMENT_FN_KEY` set-up, but the `SEGMENT_WRITE_KEY` is commented out. If you uncomment that one, do you see the event in Amplitude?

I've deleted the comment with the Loom as you could see some dev env vars. Might be worth checking with Matt on Slack whether we should change some of those env vars, just in case?

**Comment by tianrunhe** [comment]
Approving as adding `SEGMENT_WRITE_KEY` works. Please see my question on Slack [here](https://parabol.slack.com/archives/C836NA350/p1644343578729209?thread_ts=1643302326.411000&cid=C836NA350).

**Review by tianrunhe — APPROVED** [review]

**Comment by mattkrick** [comment]
LGTM!

Review time: 0 hours
