### PR TITLE
Fix Original Estimate field can not be updated in Sprint Poker

### LINKED ISSUE #5705: Sprint Poker not updating fields for Jira bug issue type
## Issue - Bug

A [customer](https://app.hubspot.com/contacts/3888472/contact/28771551) 🔒 reported the story points field in Jira on bug issue types was not updating.

I was able to reproduce the issue where Original estimate was not updating on a bug issue type. I did get the error message when I clicked 'update' and the 'fix it for me' window popped up but it timed out when I tried to give access to my Jira. You can see in the screenshot below that the original estimate field did exist for that issue type.

Screen Shot 2021-11-22 at 4 59 52 PM

Screen Shot 2021-11-22 at 4 59 41 PM

### PR DESCRIPTION
**Pull request by BartoszJarocki**
Partially fixes #5705. 

There are 2 issues there, actually. This PR fixes only the first one.
1. Time tracking fields require different body format when calling Jira API
2. When field isn't on the issue screen, our mechanism for automatically fixing that for user will fail, because `timeoriginalestimate` and `timeestimate` fields depend on the `timetracking` field being added to the issue screen. Interestin part is, when `timetracking` isn't added, but `timeoriginalestimate` is, it can't be updated via REST API, even though it can be, via Jira UI. 
More context: https://github.com/ParabolInc/parabol/issues/5705#issuecomment-1007501068 

This PR fixes 1, the second issue [has its own ticket.](https://github.com/ParabolInc/parabol/issues/5868)

Tests:
1. Make sure time tracking and original estimate fields are added to the issue screen, like that:
Screenshot 2022-01-12 at 16 35 42
2. Run sprint poker, try to update original estimate/remaining estimate fields

### CODE REVIEW

**Comment by BartoszJarocki** [comment]
@igorlesnenko do you mind checking this one?

**Review by igorlesnenko — APPROVED** [review]
Works for me. 
Weird that both `Original estimate` and `Remaining estimate` update only `Original estimate` field on Jira. Is it expected behavior?

File: packages/client/utils/AtlassianManager.ts [hunk 1]
```diff
@@ -700,15 +700,40 @@ export default abstract class AtlassianManager {
...
+    // according to Jira docs fields related to the time tracking have to be set in a different way than other fields
+    // https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-put
+    // more context: https://github.com/ParabolInc/parabol/issues/5705#issuecomment-1007501068
+    let payload: Record<string, any>
+    const timeTrackingFieldId = 'timetracking'
+    const timeTrackingFieldLookup = {
+      timeoriginalestimate: 'originalEstimate',
+      timeestimate: 'remainingEstimate'
+    }
+    const isTimeTrackingField = ['timeoriginalestimate', 'timeestimate'].includes(fieldId)
```
Comment (mattkrick) [inline packages/client/utils/AtlassianManager.ts:719]: +1 a little cleaner with 1 less variable & fewer references to magic keywords :

```ts
const timeTrackingFieldName = timeTrackingFIeldLookup[fieldId]

...
set: {
  [timeTrackingFieldName]: `${storyPoints}h`
}
```

**Review by mattkrick — APPROVED** [review]
Just 1 little way to remove some extra code, merge when ready

File: packages/client/utils/AtlassianManager.ts [hunk 2]
```diff
@@ -700,15 +700,40 @@ export default abstract class AtlassianManager {
...
+    if (isTimeTrackingField) {
+      payload = {
+        update: {
+          [timeTrackingFieldId]: [
+            {
+              set: {
+                [timeTrackingFieldLookup[fieldId]]: `${storyPoints}h`
```
Comment (mattkrick) [inline packages/client/utils/AtlassianManager.ts:726]: comment here saying h means hours
