### PR TITLE
noUncheckedIndexedAccess fixes

### LINKED ISSUE #5710: Add noUncheckedIndexedAccess to tsconfig.base (Part 2 of 3)
see #5313 for context

AC
- [ ] add `noUncheckedIndexedAccess` to tsconfig.base
- [ ] fix ~100 typescript errors
- [ ] remove `noUncheckedIndexedAcces` from tsconfig.base
- [ ] submit PR

Estimate: 4 hours

### PR DESCRIPTION
**Pull request by nickoferrall**
Fix #5710

### CODE REVIEW

File: packages/client/components/EmailPasswordAuthForm.tsx [hunk 1]
```diff
@@ -117,7 +117,9 @@ const EmailPasswordAuthForm = forwardRef((props: Props, ref: any) => {
 
   const handleBlur = async (e: React.FocusEvent<HTMLInputElement>) => {
     const {name} = e.target
-    setDirtyField(name)
+    if (name === 'email' || name === 'password') {
```
Comment (nickoferrall) [inline packages/client/components/EmailPasswordAuthForm.tsx:120]: I added extra type safety to `useForm` so that `setDirtyField` and `setValue` must use values that were passed into `useForm`. One downside is  `handleBlur` is less reusable. We could use `name!` but that's error-prone, so I think checking whether it's a valid name is the best approach.

**Comment by nickoferrall** [comment]
I think the `noUncheckedIndexedAccess` will be a big help, but one area where it's a little frustrating is when:
```
if (arr.length > 0){
    arr[0] // TypeScript says it could be undefined
}
```

The reason is we could theoretically do:
```
let a = []
a[1000] = 1 
a.length // 1001
```
However, it seems unlikely that the latter would become an issue whereas using non-null assertion operators unnecessarily will make the codebase more confusing and error-prone. 

To find some middle ground, I thought about adding a util function but discovered the following:
```
  if (arr.length && arr[0] !== undefined) {
    arr[0] // OK
  }

  const hasLength = (arr: unknown[]) => {
    return arr.length > 0 && arr[0] !== undefined
  }
  if (hasLength(arr)) {
    arr[0] // number | undefined
  }
```

It looks like the new and improved [control flow analysis](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#control-flow-analysis-of-aliased-conditions-and-discriminants) in TS 4.4 might not be working with `noUncheckedIndexedAccess`. 
I haven't seen an issue in their repo relating to this so I'll create one if you also think this is a bug.

**Comment by nickoferrall** [comment]
Hey @Dschoordsch, could you give this one a review, please?

File: packages/client/modules/userDashboard/containers/UserColumns/UserColumnsContainer.tsx [hunk 2]
```diff
@@ -85,7 +85,7 @@ const UserColumnsContainer = (props: Props) => {
       <TaskColumns
         area={areaForTaskCard}
         tasks={filteredTasks}
-        myTeamMemberId={toTeamMemberId(filteredTeams[0].id, userIds ? userIds[0] : viewer.id)}
+        myTeamMemberId={toTeamMemberId(filteredTeams[0]!.id, userIds ? userIds[0]! : viewer.id)}
```
Comment (Dschoordsch) [inline packages/client/modules/userDashboard/containers/UserColumns/UserColumnsContainer.tsx:88]: Would be nicer if you would replace the `if(filteredTeams.length)` with
```
const firstTeam = filteredTeams[0]
if (firstTeam) {
```
and then in this line with
```
        myTeamMemberId={toTeamMemberId(firstTeam.id, userIds?.[0] ?? viewer.id)}
```

File: packages/server/graphql/executeGraphQL.ts [hunk 3]
```diff
@@ -48,7 +48,7 @@ const executeGraphQL = async (req: GQLRequest) => {
   } = req
   // never re-use a dataloader since the things it cached may be old
   const dataLoader = getDataLoader(dataLoaderId)
-  dataLoader.share()
+  dataLoader?.share()
```
Comment (Dschoordsch) [inline packages/server/graphql/executeGraphQL.ts:51]: You should fix the type here instead:
https://github.com/ParabolInc/parabol/blob/3e4e15427df9b9b03d3de2a79ab0bd70e4663281/packages/server/graphql/DataLoaderCache.ts#L46-L49

File: packages/server/graphql/executeGraphQL.ts [hunk 4]
```diff
@@ -81,7 +81,7 @@ const executeGraphQL = async (req: GQLRequest) => {
     console.log((firstError as Error).stack)
     console.trace({error: JSON.stringify(response)})
   }
-  dataLoader.dispose()
+  dataLoader?.dispose()
```
Comment (Dschoordsch) [inline packages/server/graphql/executeGraphQL.ts:84]: s.a.

File: packages/server/graphql/mutations/helpers/sendMeetingJoinToSegment.ts [hunk 5]
```diff
@@ -8,7 +8,7 @@ const sendMeetingJoinToSegment = async (userId: string, newMeeting: Meeting) =>
     event: 'Meeting Joined',
     properties: {
       facilitatorUserId,
-      hasIcebreaker: phases[0].phaseType === 'checkin',
+      hasIcebreaker: phases[0]!.phaseType === 'checkin',
```
Comment (Dschoordsch) [inline packages/server/graphql/mutations/helpers/sendMeetingJoinToSegment.ts:11]: Why not stick with `?` here?

File: packages/server/graphql/mutations/helpers/sendMeetingStartToSegment.ts [hunk 6]
```diff
@@ -8,7 +8,7 @@ const sendMeetingStartToSegment = async (newMeeting: Meeting, template?: Meeting
     userId: facilitatorUserId,
     event: 'Meeting Started',
     properties: {
-      hasIcebreaker: phases[0].phaseType === 'checkin',
+      hasIcebreaker: phases[0]!.phaseType === 'checkin',
```
Comment (Dschoordsch) [inline packages/server/graphql/mutations/helpers/sendMeetingStartToSegment.ts:11]: Why not stick with `?` here?

File: packages/server/graphql/mutations/helpers/sendPokerMeetingRevoteToSegment.ts [hunk 7]
```diff
@@ -14,7 +14,7 @@ const sendPokerMeetingRevoteToSegment = async (
       userId,
       event: 'Poker Meeting Team Revoted',
       properties: {
-        hasIcebreaker: phases[0].phaseType === 'checkin',
+        hasIcebreaker: phases[0]!.phaseType === 'checkin',
```
Comment (Dschoordsch) [inline packages/server/graphql/mutations/helpers/sendPokerMeetingRevoteToSegment.ts:17]: Why not stick with `?` here?

**Review by Dschoordsch — CHANGES_REQUESTED** [review]

File: packages/client/hooks/useMakeStageSummaries.ts [hunk 8]
```diff
@@ -50,12 +50,12 @@ const useMakeStageSummaries = (phaseRef: any, localStageId: string) => {
...
     const summaries = [] as StageSummary[]
     for (let i = 0; i < stages.length; i++) {
-      const stage = stages[i]
+      const stage = stages[i]!
       const {taskId, task} = stage
       const batch = [stage]
       for (let j = i + 1; j < stages.length; j++) {
         const nextStage = stages[j]
-        if (nextStage.taskId !== taskId) break
+        if (nextStage?.taskId !== taskId) break
```
[the remark this answers is not in the document]
Comment (nickoferrall) [reply packages/client/hooks/useMakeStageSummaries.ts:58]: If we add an `!` here, the line below will complain as `nextStage` could be undefined

File: packages/client/components/EditorLinkChanger/EditorLinkChanger.tsx [hunk 9]
```diff
@@ -125,16 +125,16 @@ const EditorLinkChanger = (props: Props) => {
           <TextBlock>
             <InputLabel>{'Text'}</InputLabel>
             <InputBlock>
-              <BasicInput {...fields.text} onChange={onChange} autoFocus name='text' />
+              <BasicInput {...fields.text!} onChange={onChange} autoFocus name='text' />
```
[the remark this answers is not in the document]
Comment (nickoferrall) [reply packages/client/components/EditorLinkChanger/EditorLinkChanger.tsx]: Nice! I was hesitant to refactor as I figure we should probably use `useForm` instead of `withForm`, but this is a strong improvement from the non-nullable operators I was using previously

File: packages/server/graphql/mutations/helpers/sendMeetingStartToSegment.ts (hunk 6 above)
Comment (Dschoordsch) [reply packages/server/graphql/mutations/helpers/sendMeetingStartToSegment.ts:11]: Why not `?`?

**Review by Dschoordsch — APPROVED** [review]
Just one tiny comment, you probably just missed, can move to maintainer review afterwards.

File: packages/server/graphql/mutations/helpers/sendMeetingStartToSegment.ts (hunk 6 above)
Comment (nickoferrall) [reply packages/server/graphql/mutations/helpers/sendMeetingStartToSegment.ts]: Thanks, @Dschoordsch, I missed that one. Update pushed! I'll move it to Maintainer Review

File: packages/client/hooks/useForm.tsx [hunk 10]
```diff
@@ -44,7 +46,7 @@ type FormAction = SetError | SetDirty | SetValue
 const reducer = (state: FieldState<any>, action: FormAction) => {
   switch (action.type) {
     case 'setDirty':
-      if (state[action.name].dirty) return state
+      if (state[action.name]?.dirty) return state
```
Comment (mattkrick) [inline packages/client/hooks/useForm.tsx:49]: +2 great work fixing setDirty & friends! 


-1 you can remove all of the conditional access things in this file if you do the following:

```ts
interface SetError<T extends string> {
  type: 'setError'
  name: T
  error: string | undefined
}

interface SetDirty<T extends string> {
  type: 'setDirty'
  name: T
}

interface SetValue<T extends string> {
  type: 'setValue'
  name: T
  value: string
}

type FormAction<T extends string> = SetError<T> | SetDirty<T> | SetValue<T>

...
  const [state, dispatch] = useReducer<Reducer<FieldState<T>, FormAction<FieldStateKey<T>>>>(
```

File: packages/client/utils/relay/fromTeamMemberId.ts [hunk 11]
```diff
@@ -1,6 +1,6 @@
 const fromTeamMemberId = (teamMemberId: string) => {
   const [userId, teamId] = teamMemberId.split('::')
-  return {userId, teamId}
+  return {userId, teamId} as {userId: string; teamId: string}
```
Comment (mattkrick) [inline packages/client/utils/relay/fromTeamMemberId.ts:3]: +2 nice work avoiding the scope creep of refactoring to `TeamMemberId.split`!

**Review by mattkrick — CHANGES_REQUESTED** [review]
-1 Just 1 little change to make, otherwise good to merge!

File: packages/client/hooks/useForm.tsx (hunk 10 above)
Comment (mattkrick) [reply packages/client/hooks/useForm.tsx:49]: ping on this issue @nickoferrall

Comment (nickoferrall) [reply packages/client/hooks/useForm.tsx]: Thanks, @mattkrick. I was away on Thursday & Friday, so just getting to this now. Update pushed, and I'll now merge!
