### PR TITLE
fix: Icebreaker editing is not working properly on Android

### LINKED ISSUE #5555: Icebreaker editing is not working properly on Android
### How to reproduce
Start a meeting with icebreaker from Android device (Android 10, Moto One Vision), edit the icebreaker question manually. Try removing words.

### Expected
I can edit and remove words like in other text fields.

### Actual
The word is re-added again and again

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

### PR DESCRIPTION
**Pull request by gitstart-parabol**
# Description

Fixes #5555
Removed word are replaced back when manually editing Icebreaker question.

### Step To Reproduce
  - Launch the app using Android (MOTO ONE VISION, ANDROID 10) 
  - Start a meeting with an icebreaker
  - Try removing the existing question

## Demo

https://www.loom.com/share/9cd566aa3f4348cdb20dc2ff9dbb11e6

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Try removing the existing question on Icebreaker meeting

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by gitstart-parabol** [comment]
@igorlesnenko this PR is ready for review

**Comment by gitstart-parabol** [comment]
@BartoszJarocki this PR is ready for review

**Comment by gitstart-parabol** [comment]
@BartoszJarocki what's the verdict on this?

File: packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx [hunk 1]
```diff
@@ -117,6 +128,7 @@ const NewCheckInQuestion = (props: Props) => {
         readOnly={!isFacilitating}
         placeholder='e.g. How are you?'
         editorRef={editorRef}
+        updateAndroidQuestion={updateQuestionAndroidFallback}
```
Comment (BartoszJarocki) [inline packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx:131]: -1 to make it consistent I'd name this prop something like `setEditorStateFallback`, this will make it clear it'll only be called when normal editor isn't working

**Review by BartoszJarocki — CHANGES_REQUESTED** [review]
Just one thing otherwise looks good!

**Review by BartoszJarocki — APPROVED** [review]

**Comment by Dschoordsch** [comment]
@BartoszJarocki please assign the PR to a maintainer next time if you're not going to merge it.

**Comment by BartoszJarocki** [comment]
whoops, sure thing. somehow forgot to do that, sorry!

**Review by Dschoordsch — CHANGES_REQUESTED** [review]
Does not work on the Motorola Vision One with Android 11:
not being the facilitator
Screenshot_20230222-195818
as facilitator
Screenshot_20230222-181420

**Comment by gitstart** [comment]
Hello @Dschoordsch, we have tracked down and fixed the edge case successfully, thanks for the catch.

**Comment by gitstart-parabol** [comment]
Hello @Dschoordsch, the edge case has been tracked down and fixed successfully, thanks for the catch.

**Comment by gitstart-parabol** [comment]
@Dschoordsch this PR is ready for review.

**Review by Dschoordsch — CHANGES_REQUESTED** [review]
It works now, but the font is still wrong on the phone. It uses a monospaced font whereas the normal desktop view has a different one
Screenshot_20230302-165522

**Comment by Dschoordsch** [comment]
@gitstart-parabol please wait before implementing my last requested changes. I just saw this monospace editing text in other places and it needs verification from a designer first.
@enriquesanchez I saw that editing the Standup title or prompt uses a monospace font different from the display font when not editing. Given this is one of the newer features, is this the way to go in the future? See above screenshot.

**Comment by BartoszJarocki** [comment]
@Dschoordsch Standup uses the same component for editing meeting title as other meeting types, ie. `EditableText` and we haven't change any font settings. Maybe something has changed, maybe bug somewhere?

**Review by Dschoordsch — APPROVED** [review]
Let's just go with it and investigate the monospace font issue separately
