### PR TITLE
fix: normalize smart quote to regular quote before comparison

### LINKED ISSUE #10256: Can't delete a team
I'm unable to delete a team. I could not get the button to active, even after I entered the complete team name. The team name does have an ' in the name, "Kendra Dixon’s Team". Questioning if that is the issue as I tested adding/deleting a team named "Test" and it worked fine.

- **OS:** macOS
- **Browser:** Chrome

Image

### PR DESCRIPTION
**Pull request by ericgpark**
# Description

Fixes #10256

This is a simple change that converts any smart quotes within the team name input into regular quotes before comparing it with the actual team name. This has been known to prevent users from deleting a team, because the condition for the button enablement is tied to the team name comparison. This fix should allow users to input smart quotes and still get an accurate comparison of the team name vs input.

## Demo

Loom coming in a bit!

## Testing scenarios

- [ ] Scenario A
  - Step 1: Create a team instance within the current org (organization -> settings & members -> teams -> add team)
  - Step 2: Click the button to delete the newly created team
  - Step 3: Type in the team name in order to enable the delete button
  - Step 4: Replace the normal quote with the smart quote (copy from here: `’`)
  - Step 5: The button should be enabled
 

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label https://github.com/ParabolInc/parabol/labels/Skip%20Maintainer%20Review if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

File: packages/client/components/DeleteTeamDialog.tsx [hunk 1]
```diff
@@ -37,6 +37,17 @@ const DeleteTeamDialog = (props: Props) => {
     history.push(`/me/organizations/${teamOrgId}/teams`)
   }
 
+  const handleTypeTeamName = (e: React.ChangeEvent<HTMLInputElement>) => {
+    e.preventDefault()
+
+    // Convert smart quote to regular quote before comparison
+    if (e.target.value.replaceAll(`’`, `'`) === teamName) {
```
Comment (mattkrick) [inline packages/client/components/DeleteTeamDialog.tsx]: should we perform that same normalization on the teamName itself?

Comment (ericgpark) [reply packages/client/components/DeleteTeamDialog.tsx]: Good call, change will be up shortly.

**Review by Dschoordsch — APPROVED** [review]
