### PR TITLE
fix: Profile name length should have the upper limit

### LINKED ISSUE #7252: Profile name length should have the upper limit
## Issue - Bug

It causes UI issues:

Screenshot 2022-10-05 232211

Screenshot 2022-10-05 232334

### PR DESCRIPTION
**Pull request by gitstart**
# Description

Fixes #7252

## Demo 
[loom](https://www.loom.com/share/5a8cc6a276b64ea4b75966c4ddaf2c97)

## Testing scenarios

- [x] Scenario A
- Open the profile section, updated the user name a length greater than 50 characters

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by gitstart-parabol** [comment]
@igorlesnenko this PR is ready for review

File: packages/client/components/EditingStatus/EditingStatus.tsx [hunk 1]
```diff
@@ -26,7 +26,10 @@ const StatusHeader = styled('div')({
 })
 
 const EditingText = styled('span')<{isEditing: boolean}>(({isEditing}) => ({
-  cursor: isEditing ? 'default' : 'pointer'
+  cursor: isEditing ? 'default' : 'pointer',
+  overflowWrap: 'break-word',
+  wordWrap: 'break-word',
+  inlineSize: 50
```
Comment (igorlesnenko) [inline packages/client/components/EditingStatus/EditingStatus.tsx:32]: Why do we need exactly `inlineSize` property? Would `max-width` or `width` work?

File: packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterUserAssigneeMenu.tsx [hunk 2]
```diff
@@ -40,6 +41,12 @@ const gqlQuery = graphql`
     }
   }
 `
+const HeadName = styled('div')({
```
Comment (igorlesnenko) [inline packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterUserAssigneeMenu.tsx:44]: +1 Let's make naming consistent with other elements: `<MenuName>`

File: packages/client/components/NullCard/NullCard.tsx [hunk 3]
```diff
@@ -16,6 +16,12 @@ const AddingHint = styled('div')({
   textAlign: 'center'
 })
 
+const HeadName = styled('div')({
```
Comment (igorlesnenko) [inline packages/client/components/NullCard/NullCard.tsx:19]: +1 Let's make naming consistent with other elements, as there is no Head. For example just `<Name>`

File: packages/client/components/EditingStatus/EditingStatusText.tsx [hunk 4]
```diff
@@ -30,6 +31,12 @@ const useTimeFrom = (timestamp: string) => {
   return timeFrom
 }
 
+const HeaderName = styled('div')({
```
Comment (igorlesnenko) [inline packages/client/components/EditingStatus/EditingStatusText.tsx:34]: +1 Let's make naming consistent with other elements, as there is no Header. For example just `<Name>`

**Review by igorlesnenko — CHANGES_REQUESTED** [review]
Now menu button is out of the box:

image


Can we also fix a name if anonymous reflections are disabled in retrospective settings?

image

**Comment by gitstart** [comment]
@igorlesnenko, please check the code as the necessary cleanups have been made.

File: packages/client/components/PreferredName.tsx [hunk 5]
```diff
@@ -0,0 +1,10 @@
+import styled from '@emotion/styled'
+
+const PreferredName = styled('div')({
```
Comment (igorlesnenko) [inline packages/client/components/PreferredName.tsx:3]: I see we import this component but override most of props. 

For example here: https://github.com/ParabolInc/parabol/pull/7425/files#diff-4f66bc73bb9d80ee94155a5e5adba61a44881f2ba7cea2fb7a9c47bdc8e92570R9-R15

This does not feel generic enough to be a separate component.

Lets better remove this component and specify all props locally.

**Review by igorlesnenko — CHANGES_REQUESTED** [review]
Let's try to avoid hardcoding exact numbers for `width` when possible. Hardcoded numbers are fragile for future changes to the components design.

1) For example, some places may be fixed by setting width 100% to the parent container

image

2) In some places it works without specifying width at all, for example here

image

**Comment by gitstart** [comment]
@igorlesnenko, review comments have been attended to, please take another look.

File: packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx [hunk 6]
```diff
@@ -86,7 +90,10 @@ const ResponseCardFooter = styled('div')({
 
 export const TeamMemberName = styled('h3')({
   padding: '0 8px',
-  margin: 0
+  margin: 0,
+  width: '90%',
```
Comment (igorlesnenko) [inline packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx:94]: I think instead of hardcoding a number we can do the following

image


image

File: packages/client/components/ThreadedItemHeaderDescription.tsx [hunk 7]
```diff
@@ -19,7 +19,9 @@ const HeaderDescription = styled('div')({
 
 const HeaderName = styled('div')({
   color: PALETTE.SLATE_700,
-  fontWeight: 600
+  fontWeight: 600,
+  overflowWrap: 'break-word',
+  width: 200
```
Comment (igorlesnenko) [inline packages/client/components/ThreadedItemHeaderDescription.tsx:24]: We now have markup broken in the discussion section:

Now:
image

Was:

image

**Review by igorlesnenko — CHANGES_REQUESTED** [review]
Almost good, just a couple of fixes:

**Review by igorlesnenko — APPROVED** [review]
Thanks! It works now!

**Review by Dschoordsch — CHANGES_REQUESTED** [review]

**Comment by Dschoordsch** [comment]
@gitstart Please don't force-push between reviews, this makes the next round of reviews unnecessarily difficult.

**Comment by gitstart-parabol** [comment]
> @gitstart Please don't force-push between reviews, this makes the next round of reviews unnecessarily difficult.

Duly noted @Dschoordsch, apologies for this.

**Review by Dschoordsch — APPROVED** [review]
Tested, looks good!
