### PR TITLE
fix: Fix duplicate organizations for teams with auto join

### LINKED ISSUE #9229: Org showing up multiple times after auto join
@acressall shared the bug here: https://parabol.slack.com/archives/C042E8PGPD4/p1700530049859259

### AC

- [ ] Org only shows up once after auto joining multiple teams in the same org

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Fixes #9229 

If an organization had multiple teams with `autoJoin` enabled, multiple `OrganizationUser` objects would be created for a new user.

This fixes the creation of duplicate `OrganizationUser` objects but does not fix the existing duplicates. Ideally we would add a migration for this, but filtering over all `OrganizationUser` entries is expensive and only the Parabol org is affected.

## Testing scenarios

- [ ] create a qualified org (founder has their email verified) with 2 `autoJoin` teams and an active domain `example.com`
- [ ] create a new verified user with `test@example.com`
- [ ] see only 1 `OrganizationUser` is created
  ```graphql
  query User {
    user(email: "test@example.com") {
      organizationUsers {
        id
        userId
        orgId
      }
    }
  }
  ```

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

File: packages/server/dataloader/customLoaderMakers.ts [hunk 1]
```diff
@@ -768,13 +768,16 @@ export const autoJoinTeamsByOrgId = (parent: RootDataLoader) => {
...
-        .selectFrom('Team')
-        .where('orgId', 'in', verifiedOrgIds)
-        .where('autoJoin', '=', true)
-        .where('isArchived', '!=', true)
-        .selectAll()
-        .execute()) as unknown as Team[]
+      const teams =
+        verifiedOrgIds.length === 0
+          ? []
+          : ((await pg
```
Comment (Dschoordsch) [inline packages/server/dataloader/customLoaderMakers.ts:774]: Found this while debugging, if there were no matching teams we would return a syntax error from PG instead of an empty array. Did not break anything as the caller used `.filter(isValid)`.

File: packages/server/billing/helpers/adjustUserCount.ts [hunk 2]
```diff
@@ -97,10 +97,16 @@ const addUser = async (orgIds: string[], user: IUser, dataLoader: DataLoaderWork
       (oldOrganizationUser && oldOrganizationUser.newUserUntil) ||
       organization.periodEnd ||
       new Date()
-    return new OrganizationUser({orgId, userId, newUserUntil, tier: organization.tier})
+    return new OrganizationUser({
+      id: oldOrganizationUser?.id,
```
Comment (Dschoordsch) [inline packages/server/billing/helpers/adjustUserCount.ts:101]: If there is an existing organization user, we overwrite it. Previously we would just insert additional ones.

**Review by nickoferrall — APPROVED** [review]
Thanks for the fix!

**Comment by mattkrick** [comment]
@Dschoordsch it looks like this produced a flaky test result for me-- failed first test, passed on second try. 

https://github.com/ParabolInc/parabol/actions/runs/7278378730/job/19832437203. Should I make an issue for this?

**Comment by Dschoordsch** [comment]
@mattkrick To me it looks like the test is working fine, but I didn't fix the underlying problem completely resulting in duplicate `OrganizationUser` objects being created in some cases.
