### PR TITLE
fix: add delete confirmation button and waiting effect

### LINKED ISSUE #6424: Delete a team doesn't work until page is refreshed
I noticed that when I try to delete a team, it looks like nothing happens. But once I refresh the page the team is gone. 

@tianrunhe is able to see the team disappear from the sidebar after waiting for a few seconds. I had no such luck. 

Maybe there could be a little message saying "your team was successfully deleted"? Or some sort of "poof" animation as it disappears from the sidebar? 😅

Here's an awful drunken house drawing: 

Screen Shot 2022-04-19 at 5 11 33 PM

### PR DESCRIPTION
**Pull request by JimmyLv**
# Description

Fixes #6424

> I noticed that when I try to delete a team, it looks like nothing happens. But once I refresh the page the team is gone.

The 'delete team' feature should work, but the user interaction just makes it confusing, because: 
1. **The delete operation takes time**, but there is no indicator, like a loading effect when deleting. Only after deleted, there's a snackbar message "team has been archived"
2. **The confirmation button is not clear**, we use the text hint to confirm using the `Enter`, but using a red delete confirmation button like GitHub does might be clearer.

This PR added improvements for adding a **confirmation red button with the updated copy text and the waiting effect when deleting in progress**.

Google Chrome-Team Settings  Yet Another Roam Team-000800-20221107

## Demo

Before|After
----|----
<video src="https://user-images.githubusercontent.com/4997466/200275426-a261f1ee-e144-4e93-9b30-7c4e215bfd20.mp4" />|<video src="https://user-images.githubusercontent.com/4997466/200275400-29b9fb12-20c2-491c-99a6-57d9e4f7b84e.mp4" />

## Testing scenarios

- [ ] Delete Team
  - create new test team
  - click 'delete team'
  - type the test team name
  - click the red button or hit "Enter"
  - waiting for deleted
  - see the snackbar message

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

File: packages/client/modules/teamDashboard/components/ArchiveTeam/ArchiveTeamForm.tsx [hunk 1]
```diff
@@ -51,30 +72,32 @@ const ArchiveTeamForm = (props: Props) => {
...
         error={dirty ? error : undefined}
         onChange={onChange}
         autoFocus
-        onBlur={handleFormBlur}
         name='archivedTeamName'
-        placeholder='E.g. "My Team"'
+        placeholder={teamName}
       />
+      <ButtonGroup>
+        <SubmitButton type='submit' waiting={submitting}>
```
Comment (BartoszJarocki) [inline packages/client/modules/teamDashboard/components/ArchiveTeam/ArchiveTeamForm.tsx:94]: +1 can we disable this button until the user enters a team name?

**Review by BartoszJarocki — APPROVED** [review]
good stuff!

**Comment by BartoszJarocki** [comment]
@mattkrick do you mind taking a look? thanks!
