### PR TITLE
Fix some no implicit any errors

### LINKED ISSUE #5696: Add noImplicitAny to server tsconfig (Part 4 of 8)
When we migrated to typescript from javascript, it was too expensive to turn on `noImplicitAny` because it was hard enough just making the switch.

Today, having `noImplicitAny` could catch a lot of errors that I'm seeing in code reviews.
The problem is that there are 1600 errors!
This is too many for any one person to do in a sprint.
However, the benefit of having this turned on for new code is pretty great.

So, I propose we share the love & chip away at it:
- [ ] turn on `noImplicitAny` in the server tsconfig file
- [ ] fix ~200 errors
- [ ] turn it off again in the tsconfig file & submit the PR
- [ ] we'll merge it blindly
- [ ] create a copy of this issue named Part (3 of 8) so we can re-prioritize for the next person. We'll keep doing this until it's done

AC
- [ ] 200+ `noImplicitAny` errors are fixed in the server package

Estimate: 4 hours

### PR DESCRIPTION
**Pull request by BartoszJarocki**
Fixes #5696 

Before: `parabol-server: Found 755 errors.`
After: `parabol-server: Found 567 errors.`

### CODE REVIEW

File: packages/server/dataloader/atlassianLoaders.ts [hunk 1]
```diff
@@ -83,7 +86,9 @@ export const freshAtlassianAuth = (parent: RootDataLoader) => {
   )
 }
 
-export const jiraRemoteProject = (parent: RootDataLoader) => {
+export const jiraRemoteProject: (
+  parent: RootDataLoader
+) => DataLoader<JiraRemoteProjectKey, JiraProject | null, string> = (parent: RootDataLoader) => {
```
Comment (BartoszJarocki) [inline packages/server/dataloader/atlassianLoaders.ts:91]: This is interesting. TS can't figure out it because there's a call to parent and it requires to specify the type explicitly.  

`implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)`

File: packages/server/dataloader/atlassianLoaders.ts [hunk 2]
```diff
@@ -109,7 +114,11 @@ export const jiraRemoteProject = (parent: RootDataLoader) => {
   )
 }
 
-export const jiraIssue = (parent: RootDataLoader) => {
+export const jiraIssue: (
+  parent: RootDataLoader
+) => DataLoader<JiraIssueKey, JiraGetIssueRes['fields'] | null, string> = (
+  parent: RootDataLoader
+) => {
```
Comment (BartoszJarocki) [inline packages/server/dataloader/atlassianLoaders.ts:121]: Same

File: packages/server/dataloader/atlassianLoaders.ts [hunk 3]
```diff
@@ -181,7 +190,9 @@ export const jiraIssue = (parent: RootDataLoader) => {
 interface CloudNameLookup {
   [cloudId: string]: string
 }
-export const atlassianCloudNameLookup = (parent: RootDataLoader) => {
+export const atlassianCloudNameLookup: (
+  parent: RootDataLoader
+) => DataLoader<TeamUserKey, CloudNameLookup, string> = (parent: RootDataLoader) => {
```
Comment (BartoszJarocki) [inline packages/server/dataloader/atlassianLoaders.ts:195]: Same

File: packages/server/dataloader/atlassianLoaders.ts [hunk 4]
```diff
@@ -211,7 +222,9 @@ interface CloudNameKey extends TeamUserKey {
   cloudId: string
 }
 
-export const atlassianCloudName = (parent: RootDataLoader) => {
+export const atlassianCloudName: (
+  parent: RootDataLoader
+) => DataLoader<CloudNameKey, string, string> = (parent: RootDataLoader) => {
```
Comment (BartoszJarocki) [inline packages/server/dataloader/atlassianLoaders.ts:227]: Same

File: packages/server/graphql/types/User.ts [hunk 5]
```diff
@@ -512,10 +511,11 @@ const User: GraphQLObjectType<any, GQLContext> = new GraphQLObjectType<any, GQLC
             }
           }
         }
-        return dataLoader
+        const retroReflectionGroups = await dataLoader
           .get('retroReflectionGroups')
           .loadMany(Array.from(currentResultGroupIds))
-          .filter(isValid)
+
+        return retroReflectionGroups.filter(isValid)
```
Comment (BartoszJarocki) [inline packages/server/graphql/types/User.ts:518]: This was an actual bug, it was calling `filter` on a promise

**Comment by BartoszJarocki** [comment]
@igorlesnenko may I ask you to review this one? Thanks!

File: packages/server/graphql/mutations/createGitHubTaskIntegration.ts [hunk 6]
```diff
@@ -87,8 +87,8 @@ export default {
       )
     }
     // using teamMembers to get the preferredName as we need the members for the notification part anyways
-    const {preferredName: viewerName} = teamMembers.find(({userId}) => userId === viewerId)
-    const {preferredName: assigneeName} =
+    const {preferredName: viewerName} = teamMembers.find(({userId}) => userId === viewerId)!
```
Comment (igorlesnenko) [inline packages/server/graphql/mutations/createGitHubTaskIntegration.ts:90]: If `not-null` is not obvious directly from the code above, I would suggest using some check instead of `!`

File: packages/server/graphql/mutations/inviteToTeam.ts [hunk 7]
```diff
@@ -140,8 +134,8 @@ export default {
             inviteLink: makeAppURL(appOrigin, `team-invitation/${invitation.token}`, options),
             inviteeName: user ? user.preferredName : '',
             inviteeEmail: invitation.email,
-            inviterName: inviter.preferredName,
-            inviterEmail: inviter.email,
+            inviterName: inviter!.preferredName,
```
Comment (igorlesnenko) [inline packages/server/graphql/mutations/inviteToTeam.ts:137]: I would use some check like `if (!inviter) throw error`, if not obvious directly from code above that `null` is impossible. What do you think?

File: packages/server/graphql/mutations/promoteNewMeetingFacilitator.ts [hunk 8]
```diff
@@ -44,7 +40,7 @@ export default {
 
     // VALIDATION
     const newFacilitator = await dataLoader.get('users').load(facilitatorUserId)
-    if (!newFacilitator.tms.includes(teamId)) {
+    if (!newFacilitator!.tms.includes(teamId)) {
```
Comment (igorlesnenko) [inline packages/server/graphql/mutations/promoteNewMeetingFacilitator.ts:43]: Maybe something like `if (!newFacilitator?.tms?.includes(teamId))`

File: packages/server/graphql/mutations/removeTeamMember.ts [hunk 9]
```diff
@@ -41,7 +41,7 @@ export default {
     const {user, notificationId, archivedTaskIds, reassignedTaskIds} = res
 
     const teamMembers = await dataLoader.get('teamMembersByTeamId').load(teamId)
-    const {tms} = user
+    const {tms} = user!
```
Comment (igorlesnenko) [inline packages/server/graphql/mutations/removeTeamMember.ts:44]: Maybe check if user exists, feels not very obvious by looking at lines above
```
const res = await removeTeamMember(teamMemberId, {evictorUserId}, dataLoader)
const {user, notificationId, archivedTaskIds, reassignedTaskIds} = res
```

File: packages/server/graphql/mutations/updateCreditCard.ts [hunk 10]
```diff
@@ -36,7 +36,7 @@ export default {
 
     // RESOLUTION
     const viewer = await dataLoader.get('users').load(viewerId)
-    await upgradeToPro(orgId, stripeToken, viewer.email)
+    await upgradeToPro(orgId, stripeToken, viewer!.email)
```
Comment (igorlesnenko) [inline packages/server/graphql/mutations/updateCreditCard.ts:39]: I would prefer to have checks in these cases. As theoretically, it is not guaranteed that the viewer would exist, even if there is a small possibility. 
But not sure, we can try to formalize rules where `!` is acceptable. 
What if we disable `!` at all?
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-non-null-assertion.md

File: packages/server/utils/updateHubspot.ts [hunk 11]
```diff
@@ -395,7 +398,7 @@ const updateHubspot = async (event: string, user: IUser, properties: BulkRecord)
     const parabolPayload = await parabolFetch(query, {userIds, userId})
     if (!parabolPayload) return
     const {users, company} = parabolPayload
-    const facilitator = users.find((user) => user.id === userId)
+    const facilitator = users.find((user: any) => user.id === userId)
```
Comment (igorlesnenko) [inline packages/server/utils/updateHubspot.ts:401]: Is it fine to put any here? Is it possible to avoid it?

**Review by igorlesnenko — APPROVED** [review]
Some non-critical concerns, but otherwise looks good

File: packages/server/graphql/types/User.ts [hunk 12]
```diff
@@ -621,7 +619,7 @@ const User: GraphQLObjectType<any, GQLContext> = new GraphQLObjectType<any, GQLC
         }
       },
       resolve: async (_source: unknown, {userId}, {authToken, dataLoader}) => {
-        const userOnTeam = await dataLoader.get('users').load(userId)
+        const userOnTeam = (await dataLoader.get('users').load(userId))!
```
[the remark this answers is not in the document]
Comment (BartoszJarocki) [reply packages/server/graphql/types/User.ts:622]: def fix with runtime check

File: packages/server/graphql/mutations/addMissingJiraField.ts [hunk 13]
```diff
@@ -82,7 +82,7 @@ const addMissingJiraField = {
         dimensionField.cloudId === cloudId &&
         dimensionField.projectKey === projectKey
     )
-    const {fieldType, fieldId}: {fieldType: 'string' | 'number'; fieldId: string} = dimensionField
+    const {fieldType, fieldId} = dimensionField!
```
[the remark this answers is not in the document]
Comment (BartoszJarocki) [reply packages/server/graphql/mutations/addMissingJiraField.ts]: done!

File: packages/server/graphql/intranetSchema/mutations/messageAllSlackUsers.ts [hunk 14]
```diff
@@ -40,7 +37,7 @@ const messageAllSlackUsers = {
     const errors = [] as MessageSlackUserError[]
     for (const slackAuth of allSlackAuths) {
       const {botAccessToken, defaultTeamChannelId, userId} = slackAuth
-      const manager = new SlackServerManager(botAccessToken)
+      const manager = new SlackServerManager(botAccessToken!)
```
[the remark this answers is not in the document]
Comment (BartoszJarocki) [reply packages/server/graphql/intranetSchema/mutations/messageAllSlackUsers.ts]: done!

File: packages/server/graphql/mutations/createGitHubTaskIntegration.ts (hunk 6 above)
Comment (BartoszJarocki) [reply packages/server/graphql/mutations/createGitHubTaskIntegration.ts]: done!

File: packages/server/graphql/mutations/inviteToTeam.ts (hunk 7 above)
Comment (BartoszJarocki) [reply packages/server/graphql/mutations/inviteToTeam.ts]: done!

File: packages/server/graphql/mutations/removeTeamMember.ts (hunk 9 above)
Comment (BartoszJarocki) [reply packages/server/graphql/mutations/removeTeamMember.ts]: done

**Comment by BartoszJarocki** [comment]
@igorlesnenko thank you for the review, I fixed all the comments. @mattkrick do you mind giving it a look? Thanks!

File: packages/client/Atmosphere.ts [hunk 15]
```diff
@@ -137,11 +137,12 @@ export default class Atmosphere extends Environment {
 
   fetchHTTP = async (body: FetchHTTPData, connectionId?: string) => {
     const uploadables = body.payload.uploadables
-    const headers = {
+    const headers: Record<string, string> = {
```
Comment (mattkrick) [inline packages/client/Atmosphere.ts:140]: +1
using `as const` on this is slightly stronger as `headers.accept` will be guaranteed to exist

File: packages/client/utils/taskStatus.ts [hunk 16]
```diff
@@ -1,14 +1,14 @@
 import {TaskStatus, TaskStatusLabel} from '../types/constEnums'
 import {PALETTE} from '../styles/paletteV3'
 
-export const taskStatusLabels = {
+export const taskStatusLabels: Record<string, string> = {
```
Comment (mattkrick) [inline packages/client/utils/taskStatus.ts:4]: +1 `as const` (also makes this object readonly, so it'll throw an error if someone tries to mutate the object 🎉

File: packages/client/utils/taskStatus.ts [hunk 17]
```diff
@@ -1,14 +1,14 @@
...
   [TaskStatus.DONE]: TaskStatusLabel.DONE,
   [TaskStatus.ACTIVE]: TaskStatusLabel.ACTIVE,
   [TaskStatus.STUCK]: TaskStatusLabel.STUCK,
   [TaskStatus.FUTURE]: TaskStatusLabel.FUTURE
 }
 
-export const taskStatusColors = {
+export const taskStatusColors: Record<string, string> = {
```
Comment (mattkrick) [inline packages/client/utils/taskStatus.ts:11]: +1 as const

File: packages/server/graphql/meetingTypePredicates.ts [hunk 18]
```diff
@@ -0,0 +1,20 @@
+import MeetingPoker from '../database/types/MeetingPoker'
+import MeetingRetrospective from '../database/types/MeetingRetrospective'
+import MeetingAction from '../database/types/MeetingAction'
+import GenericMeetingStage from '../database/types/GenericMeetingStage'
+import EstimateStage from '../database/types/EstimateStage'
+
+export const isRetroMeeting = (
+  meeting: MeetingPoker | MeetingRetrospective | MeetingAction
```
Comment (mattkrick) [inline packages/server/graphql/meetingTypePredicates.ts:8]: +2 love the predicates!

+1 can you create a union type like `type AnyMeeting = MeetingPoker | MeetingRetrospective | MeetingAction`? this'll probably be stored in a pg query when we refactor the meeting table, but for now it could live in rethinkDriver.ts or wherever you think is best

File: packages/server/graphql/mutations/updateCreditCard.ts [hunk 19]
```diff
@@ -35,7 +35,7 @@ export default {
     }
 
     // RESOLUTION
-    const viewer = await dataLoader.get('users').load(viewerId)
+    const viewer = (await dataLoader.get('users').load(viewerId))! // authenticated user
```
Comment (mattkrick) [inline packages/server/graphql/mutations/updateCreditCard.ts:38]: +2 nice

File: packages/server/utils/updateHubspot.ts [hunk 20]
```diff
@@ -28,7 +28,7 @@ interface BulkRecord {
   [key: string]: string | number | undefined
 }
 
-const contactKeys = {
+const contactKeys: Record<string, string> = {
```
Comment (mattkrick) [inline packages/server/utils/updateHubspot.ts:31]: +1 `as const` for these 3

**Review by mattkrick — APPROVED** [review]
just a couple nits. merge when ready!

File: packages/client/Atmosphere.ts (hunk 15 above)
Comment (BartoszJarocki) [reply packages/client/Atmosphere.ts:140]: done

File: packages/client/utils/taskStatus.ts (hunk 16 above)
Comment (BartoszJarocki) [reply packages/client/utils/taskStatus.ts:4]: good point, done!

File: packages/client/utils/taskStatus.ts (hunk 17 above)
Comment (BartoszJarocki) [reply packages/client/utils/taskStatus.ts:11]: done

File: packages/server/utils/updateHubspot.ts (hunk 20 above)
Comment (BartoszJarocki) [reply packages/server/utils/updateHubspot.ts:31]: done

File: packages/server/graphql/meetingTypePredicates.ts (hunk 18 above)
Comment (BartoszJarocki) [reply packages/server/graphql/meetingTypePredicates.ts:8]: I'm happy to do so, just one more question.
In `rethinkDriver` we already have the following
```
  NewMeeting: {
    type: MeetingRetrospective | MeetingAction | MeetingPoker
    index: 'facilitatorUserId' | 'teamId' | 'templateId'
  }
```
So currently when we fetch the meeting from db we get the union type. By adding `AnyMeeting` do we want to future proof a bit or what? I'm happy to add it, just making sure what's the purpose as for today 

BTW, do avoid more conflicts I'm going to merge this and I'll submit a little PR after clarifying the above, hope you don't mind 🙏🏻
